---
label: CUP - Homepage
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
  jumbotronContext:
    heading: Fusce dapibus, tellus ac cursus commodo, tortor mauris
    subheading: Repository
    intro: Donec ullamcorper nulla non metus auctor fringilla. Aenean lacinia bibendum nulla sed consectetur.
    centered: true
    headingcentered: true
    selectCustomContext:
      modifier: select-custom--large
      id: 1
      required: true
      options:
        - label: Gemeente Den Haag
          value: 10
          selected: true
        - label: 20
          value: 20
        - label: 50
          value: 50
        - label: 100
          value: 100

