---
label: CUP - Browse 4
status: prototype
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
    language: true
    skipLinks:
      - url: '#content'
        text: Direct naar content
  navWetContext:
    id: 2
    modifier: folders
    items:
    - title: Repository
      sub: true
      subItems:
        - stitle: frbr
          sub: true
          subItems:
          - stitle: sgd
            sub: true
            subItems:
            - stitle: 1840
              sub: true
              subItems:
              - stitle: Expression
                sub: true
                subItems:
                - stitle: Manifestation
                  sactive: true
  alertFoutief:
    heading: Ziet u een fout in deze regeling?
    text: Meld het ons op <a href="mailto:regelgeving@overheid.nl">regelgeving@overheid.nl</a>
    modifier: alert--success alert--lg icon--document
  pageactions:
    items:
    - link: '#'
      text: Permalink
      icon: icon-permalink.svg
      modal: true
    - link: '#'
      text: Downloaden
      icon: icon-download.svg
  sortContext:
    modifier:
    columns: true
    amountPerPageFilter: false
    buttonDownload: true
  steps:
    text: link
    action: /link/intern/
    steps:
      - title: frbr
      - title: sgd
      - title: area
        active: true
  sourcesContext:
    items:
    - name: SGD_1840_coordinaten_14000
      filesize: (12kb)
      files:
      - type: xml
      buttonContext:
        modifier: button--primary
        button: false
        anchor: true
        action: http://www.google.nl
        text: Downloaden
        disabled: disabled
      remark: true
      remarkText: <p>Link is niet ok.<br />Laatste controle op 18-07-2018</p>
    - name: SGD_1840_coordinaten_14001
      filesize: (14kb)
      files:
      - type: xml
      buttonContext:
        modifier: button--primary
        button: false
        anchor: true
        action: http://www.google.nl
        text: Downloaden
        disabled: disabled
      remark: true
      remarkText: <p>Link is niet ok.<br />Laatste controle op 18-07-2018</p>
    - name: SGD_1840_coordinaten_14002
      filesize: (11kb)
      files:
      - type: xml
      buttonContext:
        modifier: button--primary
        button: false
        anchor: true
        action: http://www.google.nl
        text: Downloaden
        disabled: disabled
      remark: true
      remarkText: <p>Link is niet ok.<br />Laatste controle op 18-07-2018</p>
  sourcesContext2:
    items:
    - name: Score PC4 2016
      filesize: (12kb)
      files:
      - type: jpg
      buttonContext:
        modifier: button--primary
        button: false
        anchor: true
        action: http://www.google.nl
        text: Downloaden
        disabled: disabled
      remark: true
      remarkText: <p>Link is niet ok.<br />Laatste controle op 18-07-2018</p>
  sourcesContext3:
    items:
    - name: Score PC4 2016
      filesize: (12kb)
      files:
      - type: pdf
      buttonContext:
        modifier: button--primary
        button: false
        anchor: true
        action: http://www.google.nl
        text: Downloaden
        disabled: disabled
      remark: true
      remarkText: <p>Link is niet ok.<br />Laatste controle op 18-07-2018</p>

