title: Test
status: ready
context:
  file: logo.svg
  alt: Overheid.nl logo
  nav: true
  youAreHere:
    - text: Register voor overheidsinstanties
  hamburgerButtonText: Menu
  navLinks:
    - url: '#'
      text: Zoeken
    - url: '#'
      text: uitgebreid zoeken
  skipLinks:
    - url: '#content'
      text: Direct naar content
  headerMore:
    - title: Aankondigingen over uw buurt
      description: Zoals bouwplannen en verkeersmaatregelen.
      links:
        - url: 'https://beta.overheid.nl/aankondigingen-over-uw-buurt'
          text: Naar aankondigingen over uw buurt
    - title: Dienstverlening
      description: Zoals belastingen, uitkeringen en subsidies.
      links:
        - url: 'https://beta.overheid.nl/dienstverlening'
          text: Naar dienstverlening
    - title: Beleid & regelgeving
      description: OfficiÃ«le publicaties van de overheid.
      links:
        - url: 'https://beta.overheid.nl/beleid-en-regelgeving'
          text: Naar beleid & regelgeving
    - title: Contactgegevens overheden
      description: Adressen en contactpersonen van overheidsorganisaties.
      links:
        - url: 'https://almanak.overheid.nl/onl'
          text: Naar overheidsorganisaties
variants:
  - name: With Meta Nav
    context:
      metaLinks:
      - href: '#'
        text: Attenderen
      - href: '#'
        text: Contactgegevens
      - url: "#"
        text: Uitloggen
        class: button button--logout
  - name: With Profile
    context:
      metaLinks:
      - nonlink: true
        text: Gebruiker
        class: icon icon--profile
      - profile: true
        profileContext:
          loggedIn: true
          textLoggedIn: Mijn account
          options:
            - text: Mijn abonnementen
              url: '#'
            - text: Inloggen
              url: '#'

