---
label: Reg. - Wachtwoord vergeten
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
  breadcrumbAttenderen:
    breadcrumb:
    - text: Home
      url: '#'
    - text: Berichten over uw buurt
      url: '#'
    - text: Wachtwoord vergeten
  emailInput:
    modifier:
    id: 1
    fieldLabel: E-mailadres
    fieldLabelVisible: true
    labelmodifier: accent
    fieldInstruction:
    fieldPlaceholder: Bijv. uwnaam@koop.overheid.nl
    value: uwnaam@koop.overheid.nl
  buttonSubmit:
      id: 123
      text: Bevestigen
      button: true
      inputSubmit: true
      modifier: button--primary form__button
  buttonCancel:
      id: 123
      text: Annuleren
      anchor: true
      action: '#'
      modifier: button--text
