title: Jumbotron
status: ready
context:
  name: Default
  h: h2
  heading: Welke informatie kunt u vinden in 'Berichten over uw Buurt'?
  subheading: Berichten die voor u belangrijk zijn
  content: Denk aan formele besluiten, die direct invloed op uw buurt hebben, zoals vergunningen, bouwplannen en plaatselijke regelgeving. De berichten zijn afkomstig van voornamelijk gemeenten, waterschappen en provincies en zijn in de afgelopen twee maanden gepubliceerd.
  button: Klik mij
  link: '#'
  centered: false
  intro: Dit is de intro text van de Jumbotron
variants:
  - name: Promo
    label: Promo
    context:
      modifier: jumbotron--promo
      h: h2
      centered: true
      intro: false
      button: false
  - name: Highlight
    label: Highlight
    context:
      modifier: jumbotron--highlight
      h: h1
      centered: true
      intro: Dit is de intro van de Jumbotron
      button: false

