---
title: Data overview
label: Data overzicht
context:
  value1: E-mailadres
  value2: Postcode en huisnummer
  value3: Gemeente
  value4: Berichttype
  value5: Reikwijdte
  value6: Overheidsorganisaties
