---
title: Zoekresultaten ROI
label: Zoekresultaten ROI
preview: "@preview.default"
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
  spoedpublicatiemelding:
    modifier: alert--info
    text: Lorem ipsum dolor sit amet, consectetur adipisicing elit.
  filter1:
    heading: Soort organisatie
    intro:
    items:
      - text: <a href="#">Gemeenten&nbsp;(12)</a>
      - text: <a href="#">GR&nbsp;(29)</a>
      - text: <a href="#">ZBO&nbsp;(2)</a>
      - text: <a href="#">Provincie&nbsp;(4)</a>
      - text: <a href="#">Adviesraad&nbsp;(91)</a>
  filter2:
    heading: Classificatie
    intro:
    items:
      - text: <a href="#">OIN&nbsp;(1)</a>
      - text: <a href="#">WNT&nbsp;(3)</a>
      - text: <a href="#">Arbeidsvoorwaarde overheid&nbsp;(0)</a>
      - text: <a href="#">Rechtspersoon met wettelijke taak&nbsp;(143)</a>

