---
label: BodB - Zoekres. Lijst
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
  mapContext:
    id: 1
    modifier:
    controls: false
    kpm:
      id: 1
  mapContext2:
    id: 2
    modifier:
    controls: false
    kpm:
      id: 2
  mapContext3:
    id: 3
    modifier:
    controls: false
    kpm:
      id: 3
  voorschriftenContext:
    moreless: true
    options:
    - id: checkbox-200
      text: Aanwijzingsbesluit
      name: onderwerp
    - id: checkbox-201
      text: Agenda en notulen
      name: onderwerp
    - id: checkbox-202
      text: Belastingbesluit
      name: onderwerp
    - id: checkbox-203
      text: Besluitenlijst
      name: onderwerp
    - id: checkbox-204
      text: Collectevergunning
      name: onderwerp
    - id: checkbox-205
      text: Delegatiebesluit
      name: onderwerp
    - id: checkbox-206
      text: Gemeenschappelijke regelingen
      name: onderwerp
    - id: checkbox-207
      text: Kansspelvergunning
      name: onderwerp
    - id: checkbox-208
      text: Loterijvergunning
      name: onderwerp
    - id: checkbox-209
      text: Milieu-informatie
      name: onderwerp
    - id: checkbox-2010
      text: Milieuverordening
      name: onderwerp
    - id: checkbox-2011
      text: Optochtvergunning
      name: onderwerp
    - id: checkbox-2012
      text: Peilbesluit
      name: onderwerp
    - id: checkbox-2013
      text: Register kinderopvang
      name: onderwerp
    - id: checkbox-2014
      text: Stedelijk waterplan
      name: onderwerp
    - id: checkbox-2015
      text: Streekplan
      name: onderwerp
    - id: checkbox-2016
      text: Stroomgebiedsvisie
      name: onderwerp
    - id: checkbox-2017
      text: Structuurvisie
      name: onderwerp
    - id: checkbox-2018
      text: Vaarvergunning
      name: onderwerp
    - id: checkbox-2019
      text: Ventvergunning
      name: onderwerp
    - id: checkbox-2020
      text: Vervoer gevaarlijke stoffen vergunning
      name: onderwerp
    - id: checkbox-2021
      text: Verordeningen en reglementen
      name: onderwerp
    - id: checkbox-20221
      text: Waterbeheersplan
      name: onderwerp
  bestemmingContext:
    moreless: true
    options:
    - id: checkbox-20
      text: Bestemmingsplan
      name: onderwerp
    - id: checkbox-2022
      text: Voorbereidingsbesluit
      name: onderwerp
  voorlichtingContext:
    moreless: true
    options:
    - id: checkbox-2023
      text: Aankondiging
      name: onderwerp
    - id: checkbox-2024
      text: Huisafval
      name: onderwerp
    - id: checkbox-2025
      text: Inspraak
      name: onderwerp
    - id: checkbox-2026
      text: Mededelingen
      name: onderwerp
    - id: checkbox-2027
      text: Meldingen
      name: onderwerp
    - id: checkbox-2028
      text: Openingstijden
      name: onderwerp
    - id: checkbox-2029
      text: Overig
      name: onderwerp
    - id: checkbox-2030
      text: Rectificatie
      name: onderwerp
    - id: checkbox-2031
      text: Verkiezingen
      name: onderwerp
  onderwerpContext:
    moreless: true
    options:
    - id: checkbox-2032
      text: Aanlegvergunning
      name: onderwerp
    - id: checkbox-2033
      text: Aanlegvergunning
      name: onderwerp
    - id: checkbox-2034
      text: Apv vergunning
      name: onderwerp
    - id: checkbox-2035
      text: Bodembeschermingsvergunning
      name: onderwerp
    - id: checkbox-2036
      text: Bouwvergunning
      name: onderwerp
    - id: checkbox-2037
      text: Drank- en horecavergunning
      name: onderwerp
    - id: checkbox-2038
      text: Evenementenvergunning
      name: onderwerp
    - id: checkbox-2039
      text: Exploitatievergunning
      name: onderwerp
    - id: checkbox-2040
      text: Gebruiksvergunning
      name: onderwerp
    - id: checkbox-2041
      text: Gedoogbesluit
      name: onderwerp
    - id: checkbox-2042
      text: Gehandicaptenparkeervergunning
      name: onderwerp
    - id: checkbox-2043
      text: Geluidvergunning
      name: onderwerp
    - id: checkbox-2044
      text: Grondwateronttrekkingsvergunning
      name: onderwerp
    - id: checkbox-2045
      text: Grondwatervergunning
      name: onderwerp
    - id: checkbox-2046
      text: In- en uitritvergunning
      name: onderwerp
    - id: checkbox-2047
      text: Kapvergunning
      name: onderwerp
    - id: checkbox-2048
      text: Keurvergunning
      name: onderwerp
    - id: checkbox-2049
      text: Ligplaatsvergunning
      name: onderwerp
    - id: checkbox-2050
      text: Lozingsmelding
      name: onderwerp
    - id: checkbox-2051
      text: Lozingsvergunning
      name: onderwerp
    - id: checkbox-2052
      text: Marktvergunning
      name: onderwerp
    - id: checkbox-2053
      text: Milieueffectrapportage besluit
      name: onderwerp
    - id: checkbox-2054
      text: Milieuvergunning
      name: onderwerp
    - id: checkbox-2055
      text: Monumentenvergunning
      name: onderwerp
    - id: checkbox-2056
      text: Natuurbeschermingsvergunning
      name: onderwerp
    - id: checkbox-2057
      text: Omgevingsvergunning
      name: onderwerp
    - id: checkbox-2058
      text: Ontgrondingenvergunning
      name: onderwerp
    - id: checkbox-2059
      text: Ontheffing flora en faunawet
      name: onderwerp
    - id: checkbox-2060
      text: Ontheffing ligplaatsverbod
      name: onderwerp
    - id: checkbox-2061
      text: Ontheffing stortverbod
      name: onderwerp
    - id: checkbox-2062
      text: Onttrekkingsvergunning
      name: onderwerp
    - id: checkbox-2063
      text: Reclamevergunning
      name: onderwerp
    - id: checkbox-2064
      text: Sloopvergunning
      name: onderwerp
    - id: checkbox-2065
      text: Speelautomatenvergunning
      name: onderwerp
    - id: checkbox-2066
      text: Splitsingsvergunning
      name: onderwerp
    - id: checkbox-2067
      text:  Standplaatsvergunning
      name: onderwerp
    - id: checkbox-2068
      text: Stookvergunning
      name: onderwerp
    - id: checkbox-2069
      text: Terrasvergunning
      name: onderwerp
    - id: checkbox-2070
      text: Uitstallingvergunning
      name: onderwerp
    - id: checkbox-2071
      text: Verkeersbesluit
      name: onderwerp
    - id: checkbox-2072
      text: Vestigingsvergunning
      name: onderwerp
    - id: checkbox-2073
      text: Vuurwerkvergunning
      name: onderwerp
  publicatieCustomRange:
    range: true
    placeholder: false
  publicatiedatumContext:
    moreless: true
    options:
    - id: radio-1112312312
      text: Vandaag
      name: publicatie
      checked: checked
    - id: radio-21231232
      text: Afgelopen week
      name: publicatie
    - id: radio-3312312312
      text: Afgelopen maand
      name: publicatie
    - id: radio-412312313
      text: Afgelopen 2 maanden
      name: publicatie
      disabled: disabled
    - id: radio-51222
      text: Zelf een periode kiezen
      name: publicatie
      linkedto: 1
  gebiedContext:
    moreless: true
    options:
    - id: radio-1111
      text: Berichten rond mijn adres
      name: publicaties
      checked: checked
    - id: radio-2222
      text: Berichten in mijn gemeente
      name: publicaties
  resultsContext:
    modifier: result--list--wide
    items:
    - title: AppelAfdeling 1.2.1. Algemene bepaling voor het sluiten van schriftelijke overeenkomsten onder bezwarende titel voor het verrichten van werken, leveringen of dienstent
      titleHeader: h2
      label: Nieuw vandaag
      text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus, obcaecati! Aperiam quasi debitis exercitationem ducimus! Eligendi, iusto, ut! Tempore ab sit eveniet fugit officia minus incidunt atque facilis saepe at!
      share: false
      buttons:
        - button: Bekijk publicatie
          type: primary
        - button: Bekijk op kaart
          type: secondary
          action: modal-1
          modal: true
    - title: AppelAfdeling 1.2.1. Algemene bepaling voor het sluiten van schriftelijke overeenkomsten onder bezwarende titel voor het verrichten van werken, leveringen of dienstent
      titleHeader: h2
      label: Nieuw vandaag
      text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus, obcaecati! Aperiam quasi debitis exercitationem ducimus! Eligendi, iusto, ut! Tempore ab sit eveniet fugit officia minus incidunt atque facilis saepe at!
      share: false
      buttons:
        - button: Bekijk publicatie
          type: primary
        - button: Bekijk op kaart
          type: secondary
          action: modal-2
          modal: true
    - title: AppelAfdeling 1.2.1. Algemene bepaling voor het sluiten van schriftelijke overeenkomsten onder bezwarende titel voor het verrichten van werken, leveringen of dienstent
      titleHeader: h2
      label: Nieuw vandaag
      text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus, obcaecati! Aperiam quasi debitis exercitationem ducimus! Eligendi, iusto, ut! Tempore ab sit eveniet fugit officia minus incidunt atque facilis saepe at!
      share: false
      buttons:
        - button: Bekijk publicatie
          type: primary
        - button: Bekijk op kaart
          type: secondary
          action: modal-3
          modal: true
  huisnrContext:
    modifier: input-text--medium
    labelmodifier: accent
    id: 1
    fieldLabel: Huisnummer + toev.
    fieldLabelVisible: true
    fieldInstruction:
    fieldPlaceholder: Bijv. 12A
    remove: true
  postcodeContext:
    modifier: input-text--medium
    labelmodifier: accent
    required: true
    id: 1
    fieldLabel: Postcode
    fieldLabelVisible: true
    fieldInstruction:
    fieldPlaceholder: 1234AB
    remove: true
  inputsubmitContext:
    id: 5432
    label: Verfijn uw zoekopdracht
    showLabel: false
    placeholder: Verfijn uw zoekopdracht
    button: Zoek
    modifierComponent: input-inputsubmit--s
    remove: true
  buttonswitchContext:
    text: banner
    buttons:
      - label: Lijst
        active: true
        icon: hamburger
      - label: Kaart
        icon: marker
  selectStraalContext:
    id: 1
    modifier: select-custom--large
    options:
      - label: 250 meter
        value: 250
        selected: true
      - label: 500 meter
        value: 500
      - label: 1000 meter
        value: 1000
      - label: 2000 meter
        value: 2000
      - label: Hele gemeente
        value: 9000
  contextNewsletter:
    required: true
    type: email
  jumbotronSaveContext:
    heading: Meld je aan voor de mail
    h: h2
    subheading: Deze zoekopdracht bewaren
    centered: true
    headingcentered: true
    intro: Schrijf u in en ontvang dagelijks een update in uw inbox over alles wat er bij u in de buurt gebeurt.
    inputsubmitSearchSaveContext:
      id: 102
      label: Uw e-mailadres
      showLabel: true
      placeholder: Uw e-mailadres
      button: Bevestigen
      required: true
  jumbotronChangeContext:
    heading: Welke buurt zoekt u?
    subheading: Wijzig uw zoekopdracht
    centered: true
    headingcentered: true
    huisnrContext:
      modifier: input-text--medium
      labelmodifier: accent
      id: 1
      fieldLabel: Huisnummer + toev.
      fieldLabelVisible: true
      fieldInstruction:
      fieldPlaceholder: Bijv. 12A
      remove: true
    postcodeContext:
      modifier: input-text--medium
      labelmodifier: accent
      id: 2
      fieldLabel: Postcode
      fieldLabelVisible: true
      fieldInstruction:
      fieldPlaceholder: Bijv. 12A
      required: true
      patterntype: zipcode
  jumbotron2Context:
    modifier: slim
    heading: Meld je aan voor de mail service
    h: h2
    subheading: Automatisch op de hoogte blijven van gebeurtenissen in uw buurt?
  tt1:
    id: 11
  tt2:
    id: 12
  tt3:
    id: 13
  tt4:
    id: 14
  tt5:
    id: 15
  tt6:
    id: 16
  selectContext:
      id: 876
      modifier: select-custom--large
      fieldLabel: Straal
      options:
        - label: 250m
          value: 250m
          selected: selected
        - label: 1km
          value: 1km
        - label: 2km
          value: 2km

