---
label: Multi select
status: prototype
context:
  id: 1
  placeholder: Zoeken in verzamelingen
  name: verzamelingen
  label: Maak een keuze
  helptext: Use tabulation (or down) key to access and browse suggestions after input. Confirm your choice with enter key, or esc key.
  visuallyHideLabel: false
  fieldInstruction: ''
  regularFormElement: true
  options:
    - text: Belastingen
    - text: Bouwen, wonen en leefomgeving
    - text: Cultuur, sport, vrije tijd
    - text: Defensie
    - text: Economie en ondernemen
    - text: Belastingen 4
    - text: Bouwen, wonen en leefomgeving 4
    - text: Cultuur, sport, vrije tijd 4
    - text: Defensie 4
    - text: Economie en ondernemen 4
    - text: Belastingen 3
    - text: Bouwen, wonen en leefomgeving 3
    - text: Cultuur, sport, vrije tijd 3
    - text: Defensie 3
    - text: Economie en ondernemen 3
    - text: Belastingen 2
    - text: Bouwen, wonen en leefomgeving 2
    - text: Cultuur, sport, vrije tijd 2
    - text: Defensie 2
    - text: Economie en ondernemen 2
  categories:
    - title: Swedish Cars
      options:
        - label: Volvo
          value: volvo
        - label: Saab
          value: Saab
    - title: German Cars
      options:
        - label: Mercedes
          value: mercedes
        - label: Audi
          value: audi
