---
title: Artikel
label: Artikel
status: wip
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
  sidebar:
    modifier: list--facet
    heading: OfficiÃ«le bekendmakingen
    items:
      - text: <a href="#">Veelgestelde vragen</a>
