---
label: Filter resultaten
status: ready
context:
  id: 176575675
  searchfieldPlaceholder: Typ hier uw organisatie
  Options:
    - Option: 11
      id: 12376666622
      title: Fráns 1
      short: FR
    - Option: 1
      id: 123766666
      title: Fräns 2
      short: Spanje
    - Option: 2
      id: 223723321312
      title: Fryslân 3
      short: Griekenland
    - Option: 3
      id: 3223
      title: Fràn 4
      short: Nederland
    - Option: 12222222
      id: 12372
      title: Frãn 5
      short: Spanje
    - Option: 22222222222
      id: 2237122312
      title: Från 6
      short: Griekenland
    - Option: 3222222
      id: 32373123
      title: Frān 7
      short: Nederland
    - Option: 32222221
      id: 323731232
      title: Ander land 1
      short: Nederland
    - Option: 322222212
      id: 3237312322
      title: Ander land 2
      short: Nederland
    - Option: 322222213
      id: 3237312323
      title: Ander land 3
      short: Nederland
    - Option: 322222214
      id: 3237312324
      title: Ander land 4
      short: Nederland
    - Option: 322222215
      id: 3237312325
      title: Ander land 5
      short: Nederland
    - Option: 322222216
      id: 3237312326
      title: Ander land 6
      short: Nederland
    - Option: 322222217
      id: 3237312327
      title: Ander land 7
      short: Nederland
    - Option: 322222218
      id: 3237312328
      title: Ander land 8
      short: Nederland
variants:
  - name: Input radio
    label: met Radio
    context:
      id: 176575675
      radio: true
      Options:
        - Option: 1
          id: 123766666
          title: Rotterdam
          short: Spanje
        - Option: 2
          id: 223723321312
          title: Schiedam
          short: Griekenland
        - Option: 3
          id: 3223
          title: Vlaardingen
          short: Nederland
        - Option: 12222222
          id: 12372
          title: Den Haag
          short: Spanje
        - Option: 22222222222
          id: 2237122312
          title: Scheveningen
          short: Griekenland
        - Option: 3222222
          id: 32373123
          title: Voorburg
          short: Nederland
  - name: with Controls
    label: met Controls
    context:
      controls:
        selectAllLabel: Selecteer alle organisaties
  - name: Multilevel
    context:
      id: 176575675
      Sets:
        - title: Nederland
          Options:
          - Option: 1
            id: 123766666
            title: Rotterdam
            short: Spanje
          - Option: 2
            id: 223723321312
            title: Schiedam
            short: Griekenland
          - Option: 3
            id: 3223
            title: Vlaardingen
            short: Nederland
          - Option: 12222222
            id: 12372
            title: Den Haag
            short: Spanje
          - Option: 22222222222
            id: 2237122312
            title: Scheveningen
            short: Griekenland
          - Option: 3222222
            id: 32373123
            title: Voorburg
            short: Nederland
        - title: Belgie
          Options:
          - Option: 1
            id: 1237666662
            title: Brussel
            short: Brussel
          - Option: 2
            id: 2237233213122
            title: Antwerpen
            short: Antwerpen
