---
label: Verdr. - Homepage
status: Ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
    language: true
  jumbotronContext:
    heading: Doorzoek de 3621 verdragen waarbij het Konkrijk der Nederlanden partij is
    subheading: Verdragenbank
    intro: Intro.
    centered: true
    headingcentered: true
    inputsubmitContext:
      button: Zoek verdagen
      placeholder: Vul hier uw zoekwoord(en) in
    inputSearchContext:
      modifier: input-text--searchmedium
      id: 1
      fieldLabel: Zoekwoord
      fieldLabelVisible: false
      fieldInstruction:
      fieldPlaceholder: Vul hier uw zoekwoord(en) in
      remove: true
  doubleline1Context:
    text: Overzicht verdragen in voorbereiding
    text2: officielebekendmakingen.nl
    modifier: button--doubleline button--icon-external
    action: http://www.google.nl
    anchor: true
    button: true
    iconButton: false
    inputButton: false
    inputSubmit: false
    buttonWithDivider: false
    type: submit
    disabled: ''
  doubleline2Context:
    text: Tractatenbladen en maandberichten
    text2: officielebekendmakingen.nl
    modifier: button--doubleline button--icon-external
    action: http://www.google.nl
    anchor: true
    button: true
    iconButton: false
    inputButton: false
    inputSubmit: false
    buttonWithDivider: false
    type: submit
    disabled: ''
  newsletterCheckbox:
    options:
    - id: checkbox-112312312
      text: Ik begrijp dat ...
      name: agreement
  newslCollap:
    heading: Lees meer over uw privacy
    id: 11231231
    text: Meer informatie over privacy en andere zaken
  figure:
    figcaption: false
