---
label: EB - Contentpage 2
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
    navLinks:
    - url: '#'
      text: SGD
      className: is-active
    - url: '#'
      text: '...'
    metaLinks:
      - text: Gebruiker
        class: icon icon--profile
        nonlink: true
      - url: "#"
        text: Uitloggen
        class: button button--logout
    youAreHere:
      - text: Externe Beheersite
    topbar:
      navItems:
        - label: Beheersite
          href: '#'
          active: true
        - label: Digitaal Loket
          href: '#'
        - label: Stage BMS
          href: '#'
  breadcrumb:
    title: "U bent hier:"
    breadcrumb:
    - text: Home
      url: '/components/preview/templates-eb-homepage'
    - text: SGD
      url: '#'
    - text: Spoedpublicaties
      url: '#'
    - text: Publicaties publiceren
  navToeContext:
    id: 2
    items:
    - title: SGD
      href: /components/preview/templates-eb-projectlanding
      active: true
      sub: true
      subItems:
        - stitle: Publicatieproces
        - stitle: Spoedpublicaties
          sub: true
          subItems:
            - stitle: Spoedpublicaties voorpubliceren
            - stitle: Spoedpublicaties publiceren
              sactive: true
        - stitle: Updaten metadata
        - stitle: Vervangen verschijningsvormen
        - stitle: Zoekdienst
        - stitle: Controlelijst
        - stitle: OEB ochtendcontrole
