title: KPM Lijst
label: KPM Lijst
preview: "@preview.default"
context:
  inputAutocompleteContext:
    id: 2
    modifier: input-text input-text--search
    placeholder: Zoek een adres
    name: verzamelingen
    hasHiddenField: true
    hiddenFieldClass: field-class
    visuallyHideLabel: false
    fieldInstruction: ''
    regularFormElement: true
    items:
      - item: Gemeente Vlaardingen
        code: ABC
      - item: Gemeente Schiedam
        code: DEF
      - item: Gemeente Rotterdam
        code: XYZ
      - item: Voorburg
        code: 123
  headerContext:
    youAreHere:
    - text: Kaartprikmodule
  breadcrumbContext:
    last: Kaartprikmodule
    breadcrumbs:
      - label: Home
        path: "#"
  button1Context:
    modifier: button--small
    iconButton: true
    text: Marker
  button2Context:
    modifier: button--small
    iconButton: true
    text: Download
  button4Context:
    modifier: button--small
    button: true
    text: Meer details
  button5Context:
    modifier: button--small
    button: true
    text: Toevoegen
  button6Context:
    modifier: button-icon--remove button-icon--small
    button: true
    text: Toevoegen aan lijst
  table1ExpandButtonContext:
    modifier: button--small trigger-collapse table-one-trigger
    button: true
    text: Meer details
  table2ExpandButtonContext:
    modifier: button--small trigger-collapse table-two-trigger
    button: true
    text: Meer details
  table3ExpandButtonContext:
    modifier: button--small trigger-collapse table-three-trigger
    button: true
    text: Meer details
  modalContext: "<h2 class='k-future h2--large'>Geselecteerde locatie verwijderen</h2><p>Weet u zeker dat u deze locatie wilt verwijderen?</p><h3>Gemeente 's-Gravenhage</h3><table class='table--small'><tbody><tr class='type-row'><th>Type</th><td>Gemeente</td></tr><tr class='source-row'><th>Bron</th><td>Bestuurlijke Grenzen</td></tr></tbody></table><button class='button button--inversed'>Annuleren</button><button class='button button--primary'>Verwijderen</button>"
  closeButton: Sluiten
