title: KPM Zoekresultaat
label: KPM Zoekresultaat
preview: "@preview.default"
context:
  inputAutocompleteContext:
    id: 2
    modifier: input-text input-text--search
    placeholder: Zoek een adres
    name: verzamelingen
    hasHiddenField: true
    hiddenFieldClass: field-class
    visuallyHideLabel: false
    fieldInstruction: ''
    regularFormElement: true
    items:
      - item: Gemeente Vlaardingen
        code: ABC
      - item: Gemeente Schiedam
        code: DEF
      - item: Gemeente Rotterdam
        code: XYZ
      - item: Voorburg
        code: 123
  removeResultIconContext:
    modifier: icon--cross-blue--small
    text: ""
  button4Context:
    modifier: button--small trigger-collapse table-trigger
    button: true
    text: Meer details
  button5Context:
    modifier: button--small
    button: true
    text: Centereren
  button6Context:
    modifier: button--small
    button: true
    text: Toevoegen
