name: DS - Content
label: DS - Content
context:
  header:
    nav: false
  breadcrumb:
    last: Content
    breadcrumbs:
    - label: Overheid.nl
      path: 'test'
    - label: Design system
      path: 'test'
  navMenuContext:
    items:
    - title: Design system
      active: true
      href: /
      sub: true
      subItems:
        - stitle: Content
          href: content.html
          sactive: true
        - stitle: Design
          href: ontwerpprincipes.html
        - stitle: Components
          href: componenten.html
  navContentContext:
    items:
    - title: Content
      active: false
      sub: true
      anker: true
      subItems:
        - stitle: Schrijfwijzer
          href: schrijfwijzer

