---
label: Zoeken in bekendmakingen - Wijzig Abo.
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
    youAreHere:
      - text: Publicaties > Officiële publicaties
    navLinks:
      - url: '#'
        text: Home
      - url: '#'
        text: Uitgebreid zoeken
        className: is-active
      - url: '#'
        text: 'Mijn abonnementen'
      - url: '#'
        text: Help
        modifier: secondary
    metaLinks:
      - profile: true
        profileContext:
          id: 12
          loggedIn: false
          buttonLogin:
            text: Inloggen
            anchor: true
            action: '#'
  breadcrumb:
    breadcrumb:
      - text: Home
        url: '#'
      - text: Uitgebreid zoeken
        url: '#'
      - text: Officiële bekendmakingen
  tabs:
    items:
      - content: <a href="templates-oeb-zoek-bekendmakingen" class="is-selected">Officiële bekendmakingen</a>
      - content: <a href="templates-oeb-zoek-documenten">Parlementaire documenten</a>
  jumbotronContext:
    heading: Zoek in officiële bekendmakingen
    hstyle: h2
    subheading: Officiële bekendmakingen
    intro: Met de uitgebreide zoekmogelijkheden op dit scherm kunt u gericht zoeken naar officiële bekendmakingen waarin u geïnteresseerd bent.
    centered: true
    size: semimedium
    inputZoekwoord:
      fieldPlaceholder: Zoekterm of (dossier)nummer
      fieldLabel: Zoek op trefwoord
      fieldLabelVisible: true
      labelmodifier: medium
      modifier: input-text--searchmedium
      value: Snelweg
    zoekeninContext:
      id: 560934590
      fieldLabel: Zoek in
      labelmodifier: accent
      fieldLabelVisible: true
      modifier: select-custom--large
      options:
        - label: Gehele tekst
          value: gehele-tekst
          selected: selected
        - label: Alleen titel
          value: alleen-titel
    dateselection:
      dateselectionType:
        id: 1
        fieldLabel: Periode
        fieldLabelVisible: true
        labelmodifier: accent
        hastooltip: false
        options:
          - id: 101
            value:
            label: Alle data
            linkedto: 1
          - id: 102
            value: 10
            label: Specifieke datum
            linkedto: 2
          - id: 103
            value: 30
            label: Zelf een periode kiezen
            linkedto: 3
      additionalSelect:
        id: 1678765
        fieldLabel: Datum van
        fieldLabelVisible: true
        labelmodifier: accent
        hastooltip: true
        tooltip:
          content: '<strong>Datum publicatie</strong>: De datum waarop het document is gepubliceerd op deze site. <br> <strong>Datum document</strong>: de kenmerkende datum van het document, zoals de datum van ondertekening of totstandkoming.'
          id: 123129876545678922
        options:
        - id: 1012
          value:
          label: Publicatie
          linkedto: 1
          selected: selected
        - id: 1023
          value: 10
          label: Document
      additionalSelect2:
        id: 16787654
        fieldLabel: Datum van
        fieldLabelVisible: true
        labelmodifier: accent
        hastooltip: true
        tooltip:
          content: '<strong>Datum publicatie</strong>: De datum waarop het document is gepubliceerd op deze site. <br> <strong>Datum document</strong>: de kenmerkende datum van het document, zoals de datum van ondertekening of totstandkoming.'
          id: 1231298765456789221
        options:
        - id: 10121
          value:
          label: Publicatie
          linkedto: 1
          selected: selected
        - id: 10231
          value: 10
          label: Document
      dateselectionDatum:
        label: Datum
        value: '2020-09-11'
        datavalue: '11-09-2020'
        configDateFormat: 'dd-mm-yy'
        id: 231
        haslabel: true
        labelmodifier: accent
        fieldPlaceholder: DD-MM-JJJJ
      dateselectionDatumStart:
        id: 234
        haslabel: true
        label: Vanaf
        labelmodifier: accent
        fieldPlaceholder: DD-MM-JJJJ
        value: ''
        datavalue: ''
        configDateFormat: 'dd-mm-yy'
      dateselectionDatumEnd:
        id: 345
        haslabel: true
        label: Tot en met
        labelmodifier: accent
        fieldPlaceholder: DD-MM-JJJJ
        value: '2020-09-11'
        datavalue: '11-09-2020'
        configDateFormat: 'dd-mm-yy'
    inputsubmitContext:
      button: Zoek verdagen
      placeholder: Vul hier uw zoekwoord(en) in
    buttonSubmit:
      id: 123
      text: Zoek bekendmakingen
      button: true
      type: submit
      modifier: button--primary form__button
    subselectionGemContext:
      linkText: Selecteer type organisatie(s)
      id: 20
      modalTitle: Type organisatie(s)
      label: Zoek type organisatie(s)
      inputPlaceholder: 'Zoekterm'
      searchFilter: true
      maxShow: 3
      type: span
      multilevel: false
      controls:
        selectAllLabel: "Selecteer alle type organisaties"
      Options:
        - Option: 1
          id: 1237
          title: Adviescollege
          short: Adviescollege
          checked: checked
        - Option: 2
          id: 22372312321312
          title: Deelgemeente
          short: Deelgemeente
          checked: checked
        - Option: 3
          id: 323723
          title: Dienst en agentschap
          short: Dienst en agentschap
          checked: checked
        - Option: 1222222222
          id: 1237232
          title: Gemeente
          short: Gemeente
        - Option: 2222222222222
          id: 223712312312
          title: Hoog college van staat
          short: Hoog college van staat
        - Option: 3222222221
          id: 32371231231
          title: Koepelorganisatie
          short: Koepelorganisatie
        - Option: 32222222212
          id: 32371231232
          title: Ministerie
          short: Ministerie
        - Option: 3222222223
          id: 32371231233
          title: Openbaar lichaam voor bedrijf en beroep
          short: Openbaar lichaam voor bedrijf en beroep
        - Option: 3222222224
          id: 32371231234
          title: Politiekorps
          short: Politiekorps
        - Option: 3222222225
          id: 32371231235
          title: Provincie
          short: Provincie
        - Option: 3222222226
          id: 32371231237
          title: Rechterlijke macht
          short: Rechterlijke macht
        - Option: 3222222227
          id: 32371231238
          title: Regionaal samenwerkingsorgaan
          short: Regionaal samenwerkingsorgaan
        - Option: 3222222228
          id: 32371231239
          title: Staten generaal
          short: Staten generaal
        - Option: 3222222229
          id: 323712312310
          title: Waterschap
          short: Waterschap
        - Option: 32222222271
          id: 323712312311
          title: Zelfstandig berstuurorgaan
          short: Zelfstandig berstuurorgaan
    subselectionPubContext:
      linkText: Selecteer organisatie(s)
      id: 21
      modalTitle: Publicerende organisatie(s)
      label: Zoek publicerende organisatie(s)
      inputPlaceholder: 'Zoekterm'
    subselectionWatContext:
      linkText: Selecteer onderwerp(en)
      id: 1900
      modalTitle: Onderwerp(en)
      label: Zoek onderwerp
      inputPlaceholder: 'Zoekterm'
      type: span
      searchFilter: true
      multilevel: false
      buttonResetForm: true
      controls:
        selectAllLabel: Selecteer alle onderwerpen
      Options:
        - Option: 4
          id: 44551
          title: Bestuur
          short: Bestuur
        - Option: 5
          id: 54552
          title: Cultuur en recreatie
          short: Cultuur en recreatie
        - Option: 6
          id: 64553
          title: Economie
          short: Economie
        - Option: 6
          id: 64554
          title: Financiën
          short: Financiën
        - Option: 6
          id: 64555
          title: Huisvesting
          short: Huisvesting
        - Option: 6
          id: 64556
          title: Internationaal
          short: Internationaal
        - Option: 6
          id: 64557
          title: Landbouw
          short: Landbouw
        - Option: 6
          id: 64558
          title: Migratie en integratie
          short: Migratie en integratie
        - Option: 6
          id: 64559
          title: Natuur en milieu
          short: Natuur en milieu
        - Option: 6
          id: 645510
          title: Onderwijs en waterschap
          short: Onderwijs en waterschap
        - Option: 6
          id: 645511
          title: Openbare orde en veiligheid
          short: Openbare orde en veiligheid
        - Option: 6
          id: 645512
          title: Recht
          short: Recht
        - Option: 6
          id: 645513
          title: Ruimte en infrastructuur
          short: Ruimte en infrastructuur
        - Option: 6
          id: 645514
          title: Sociale zekerheid
          short: Sociale zekerheid
        - Option: 6
          id: 645515
          title: Verkeer
          short: Verkeer
        - Option: 6
          id: 645516
          title: Werk
          short: Werk
        - Option: 6
          id: 645517
          title: Zorg en gezondheid
          short: Zorg en gezondheid
    accordion1:
      type: checkbox
      item1:
        type: checkbox
        headerId: header1
        headerLabel: Accordion Vraag 1
        contentId: con1
        hasContent: false
        accordionCheckbox:
          options:
          - id: header1
            text: Alle
            name: countries
            inputClass: js-checkbox-master
            arguments: aria-checked="true"
      item2:
        type: checkbox
        headerId: header2
        contentId: con2
        accordionCheckbox:
          options:
          - id: header2
            text: Tractatenblad
            name: countries
            inputClass: accordion__item__header-checkboxtrigger
            arguments: aria-controls="con2" aria-checked="false"
        trac_jaargang:
          id: 11112
          type: number
          fieldLabel: Jaargang
          fieldLabelVisible: true
          fieldPlaceholder: 'JJJJ'
          labelmodifier: secondary
        trac_nummer:
          id: 11113
          type: number
          fieldLabel: Nummer
          fieldLabelVisible: true
          fieldPlaceholder: 'Nummer'
          labelmodifier: secondary
        trac_onderwerpen:
          id: 11114
          multilevel: false
          linkText: Selecteer onderwerp(en)
          linkTextActive: Wijzig selectie
          modalTitle: Selecteer onderwerp(en)
          fieldLabel: fieldLabel
          inputPlaceholder: 'Zoekterm'
          label: Zoek onderwerp
          controls:
            selectAllLabel: Selecteer alle gevonden onderwerpen
          Options:
          - Option: 2112222
            id: 2112222
            title: Arbeid
            short: Arbeid
          - Option: 212
            id: 212
            title: Arbitrage
            short: Arbitrage
          - Option: 213
            id: 213
            title: Belasting
            short: Belasting
          - Option: 214
            id: 214
            title: Burgelijk procesrecht
            short: Burgelijk procesrecht
          - Option: 215
            id: 215
            title: Burgelijke stand
            short: Burgelijke stand
          - Option: 216
            id: 216
            title: Cultuur
            short: Cultuur
          - Option: 217
            id: 217
            title: Diplomatieke en consulaire betrekkingen
            short: Diplomatieke en consulaire betrekkingen
        trac_nummer2:
          id: 11115
          type: number
          fieldLabel: Nummer
          fieldLabelVisible: true
          fieldPlaceholder: 'Nummer'
          labelmodifier: secondary
        trac_jaar:
          id: 11116
          type: number
          fieldLabel: Jaar
          fieldLabelVisible: true
          fieldPlaceholder: 'JJJJ'
          labelmodifier: secondary
        trac_volgnummer:
          id: 11117
          type: number
          fieldLabel: Volgnummer
          fieldLabelVisible: true
          fieldPlaceholder: 'Volgnummer'
          labelmodifier: secondary
        trac_datepicker1:
          id: 1111811111
          haslabel: true
          label: 'Vanaf'
          labelmodifier: secondary
          fieldPlaceholder: 'DD-MM-JJJJ'
        trac_datepicker2:
          id: 1111922222
          haslabel: true
          label: 'Tot en met'
          labelmodifier: secondary
          fieldPlaceholder: 'DD-MM-JJJJ'
        trac_plaats:
          id: 11120
          type: text
          fieldLabel: Plaats
          fieldLabelVisible: true
          fieldPlaceholder: 'Plaats'
          labelmodifier: secondary
      item3:
        type: checkbox
        headerId: header3
        contentId: con3
        accordionCheckbox:
          options:
          - id: header3
            text: Staatsblad
            name: countries
            checked: checked
            inputClass: accordion__item__header-checkboxtrigger
            arguments: aria-controls="con3" aria-checked="true"
        sb_jaargang:
          id: 11121
          type: number
          fieldLabel: Jaargang
          fieldLabelVisible: true
          fieldPlaceholder: 'JJJJ'
          labelmodifier: secondary
          value: 2018
        sb_nummer:
          id: 11122
          type: number
          fieldLabel: Nummer
          fieldLabelVisible: true
          fieldPlaceholder: 'Nummer'
          labelmodifier: secondary
          value: 12
      item4:
        type: checkbox
        headerId: header4
        contentId: con4
        accordionCheckbox:
          options:
          - id: header4
            text: Staatscourant
            name: countries
            inputClass: accordion__item__header-checkboxtrigger
            arguments: aria-controls="con4" aria-checked="false"
        sc_jaargang:
          id: 11123
          type: number
          fieldLabel: Jaargang
          fieldLabelVisible: true
          fieldPlaceholder: 'JJJJ'
          labelmodifier: secondary
        sc_nummer:
          id: 11124
          type: number
          fieldLabel: Nummer
          fieldLabelVisible: true
          fieldPlaceholder: 'Nummer'
          labelmodifier: secondary
      item5:
        type: checkbox
        headerId: header5
        contentId: con5
        accordionCheckbox:
          options:
          - id: header5
            text: Gemeenteblad
            name: countries
            inputClass: accordion__item__header-checkboxtrigger
            arguments: aria-controls="con5" aria-checked="false"
        gm_jaargang:
          id: 11133
          type: number
          fieldLabel: Jaargang
          fieldLabelVisible: true
          fieldPlaceholder: 'JJJJ'
          labelmodifier: secondary
        gm_nummer:
          id: 11134
          type: number
          fieldLabel: Nummer
          fieldLabelVisible: true
          fieldPlaceholder: 'Nummer'
          labelmodifier: secondary
      item6:
        type: checkbox
        headerId: header6
        contentId: con6
        accordionCheckbox:
          options:
          - id: header6
            text: Provinciaal blad
            name: countries
            inputClass: accordion__item__header-checkboxtrigger
            arguments: aria-controls="con6" aria-checked="false"
        pb_jaargang:
          id: 11143
          type: number
          fieldLabel: Jaargang
          fieldLabelVisible: true
          fieldPlaceholder: 'JJJJ'
          labelmodifier: secondary
        pb_nummer:
          id: 11144
          type: number
          fieldLabel: Nummer
          fieldLabelVisible: true
          fieldPlaceholder: 'Nummer'
          labelmodifier: secondary
      item7:
        type: checkbox
        headerId: header7
        contentId: con7
        accordionCheckbox:
          options:
          - id: header7
            text: Waterschapsblad
            name: countries
            inputClass: accordion__item__header-checkboxtrigger
            arguments: aria-controls="con7" aria-checked="false"
        wb_jaargang:
          id: 11153
          type: number
          fieldLabel: Jaargang
          fieldLabelVisible: true
          fieldPlaceholder: 'JJJJ'
          labelmodifier: secondary
        wb_nummer:
          id: 11154
          type: number
          fieldLabel: Nummer
          fieldLabelVisible: true
          fieldPlaceholder: 'Nummer'
          labelmodifier: secondary
      item8:
        type: checkbox
        headerId: header8
        contentId: con8
        accordionCheckbox:
          options:
          - id: header8
            text: Blad gemeenschappelijke regeling
            name: countries
            inputClass: accordion__item__header-checkboxtrigger
            arguments: aria-controls="con8" aria-checked="false"
        bgr_jaargang:
          id: 11163
          type: number
          fieldLabel: Jaargang
          fieldLabelVisible: true
          fieldPlaceholder: 'JJJJ'
          labelmodifier: secondary
        bgr_nummer:
          id: 11164
          type: number
          fieldLabel: Nummer
          fieldLabelVisible: true
          fieldPlaceholder: 'Nummer'
          labelmodifier: secondary
    sc_rubrieken:
      id: 11125
      multilevel: false
      linkText: Selecteer rubriek(en)
      linkTextActive: Wijzig selectie
      modalTitle: Selecteer rubriek(en)
      fieldLabel: fieldLabel
      inputPlaceholder: 'Zoekterm'
      label: Zoek rubriek
      controls:
        selectAllLabel: Selecteer alle rubrieken
      Options:
      - Option: 11126
        id: 11126
        title: Aanbestedingen
        short: Aanbestedingen
      - Option: 11127
        id: 11127
        title: Adviezen Raad van State
        short: Adviezen Raad van State
        checked: checked
      - Option: 11128
        id: 11128
        title: Algemeenverbindendverklaring van CAO-bepalingen
        short: Algemeenverbindendverklaring van CAO-bepalingen
      - Option: 11129
        id: 11129
        title: Autorisatiebesluiten basisregistratie Personen
        short: Autorisatiebesluiten basisregistratie Personen
      - Option: 11130
        id: 11130
        title: Bekendmakingen aan de scheepvaart
        short: Bekendmakingen aan de scheepvaart
      - Option: 11131
        id: 11131
        title: Bekendmakingen aan het wegverkeer
        short: Bekendmakingen aan het wegverkeer
      - Option: 11132
        id: 11132
        title: Bekendmakingen Nederland Zorgautoriteit
        short: Bekendmakingen Nederland Zorgautoriteit
