---
title: BWB - Geselecteerde elementen
label: BWB - Geselecteerde elementen
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
    navLinks:
      - url: '#'
        text: Eenvoudig zoeken
      - url: '#'
        text: Uitgebreid zoeken
        className: is-active
      - url: '#'
        text: Zoeken in EU-richtlijnen
    youAreHere:
      - text: Wettenbank
  breadcrumb:
    title: "U bent hier:"
    breadcrumb:
      - text: Uitgebreid zoeken
        url: '#'
      - text: Zoekresultaten
        url: '#'
      - text: Aangevinkte regelingselementen
  sidebar:
    modifier: list--facet
    heading: OfficiÃ«le bekendmakingen
    items:
      - content: <a href="#">Veelgestelde vragen</a>
  actionBlock:
    items:
      - link: '#'
        text: Alles openklappen
        icon: icon-plus.svg
      - link: '#'
        text: Alles dichtklappen
        icon: icon-minus.svg
  counterFirst:
    modifier: article__header--main
    activeFrom: Geldend van 18-04-2019 t/m heden
    export: true
    exportLabel: Sla de geselecteerde elementen op
    exportHref: 'javascript:void(0)'
    exportDataAttributes: onclick="$('#hfRegelingOnderdelenActie').val('rtf'); __doPostBack('exporteernaarrtf', '');"
    print: true
    printLabel: Druk de geselecteerde elementen af
    printModalId: popupafdrukken
    printAClass: popupafdrukken
    printDataAttributes: data-onderdeelids="BWBR0032203/2019-04-18/0/Intitule,BWBR0032203/2019-04-18/0/Aanhef"
  counter:
    modifier: article__header--main
    counter: Afdeling 1.2.1. Algemene bepaling voor het sluiten van schriftelijke overeenkomsten onder bezwarende titel voor het verrichten van werken, leveringen of diensten
    activeFrom: Geldend van 18-04-2019 t/m heden
    relations: true
    relationsLabel: Toon relaties in LiDO
    relationsHref: '#'
    relationsClass: aantallen-lido
    relationsAModalId: popuplidorelaties
    relationsAClass: popuplidorelaties
    relationsAHref: /jci1.3:c:BWBR0008994&z=1998-01-01&g=1998-01-01
    relationsDataAttributes: 'data-juriconnectid="jci1.3:c:BWBR0008994&z=1998-01-01&g=1998-01-01" data-bwbngid="http://wetten.overheid.nl/id/BWBR0008994/1998-01-01/0"'
    relationsADataAttributes: "data-juriconnectverwijzing='jci1.3:c:BWBR0008994&z=1998-01-01&g=1998-01-01'"
    permalink: true
    permalinkLabel: Maak een permanente link
    permalinkAModalId: popuppermanentelink
    permalinkAClass: popuppermanentelink
    permalinkAHref: /jci1.3:c:BWBR0008994&z=1998-01-01&g=1998-01-01
    permalinkDataAttributes: data-juriconnectverwijzing="jci1.3:c:BWBR0008994&z=1998-01-01&g=1998-01-01" data-citeertitel="Aanpassingswet derde tranche Awb I" data-linktoolurl="https://linkeddata.overheid.nl/front/portal/linktool-bwb-verfijnen?ext-id=http%3a%2f%2fwetten.overheid.nl%2fid%2fBWBR0008994%2f1998-01-01%2f0&amp;geldigheidsdatum=2020-09-28&amp;zichtdatum=2021-01-27"
    version: true
    versionLabel: Toon wetstechnische informatie
    versionHref: '/BWBR0008994/1998-01-01/0/informatie'
    compare: true
    compareLabel: Versie vergelijk
    compareModalId: popupvergelijken
    compareDataAttributes: data-inwerking="21-12-2018" data-hashfragmentid="" data-bwb-id="BWBR0001840" data-toestand-id="2018-12-21" data-volgnummer="0" data-label-id=""
    compareAClass: popupvergelijken
    print: true
    printLabel: Druk de regeling af
    printModalId: popupafdrukken
    printAClass: popupafdrukken
    export: true
    exportModal: true
    exportModalId: popupexporteren
    exportLabel: Sla de regeling op
    exportAClass: popupexporteren
    exportHref: '/BWBR0001840/2018-12-21/0'
  popuplidorelaties:
    modalId: popuplidorelaties
    openButton: false
    initClosed: true
  popuppermanentelink:
    modalId: popuppermanentelink
    openButton: false
    initClosed: true
    copydata1:
      datafieldId: divCiteertitel
    copydata2:
      datafieldId: divUrl
    copydata3:
      datafieldId: divJuriconnectverwijzing
  popupafdrukken:
    modalId: popupafdrukken
    openButton: false
    initClosed: true
    modalPrintButton:
      text: Ok
    printradio:
      options:
        - id: checkbox-1
          text: Exclusief wetstechnische informatie
          name: printopties
          value: rbExclusief
          checked: checked
        - id: checkbox-2
          text: Inclusief wetstechnische informatie
          name: printopties
          value: rbInclusief
  popupvergelijken:
    modalId: popupvergelijken
    openButton: false
    initClosed: true
    modalCompareButton:
      text: Vergelijk
    compareSelect:
      id: 112
      selectClass: dlDatum
      fieldLabel: Inwerkingtreding
      options:
        - label: 01-01-2019
          value: 20
          selected: selected
        - label: 01-01-2018
          value: 20
        - label: 01-01-2017
          value: 20
        - label: 01-01-2016
          value: 20
  popupexporteren:
    modalId: popupexporteren
    openButton: false
    initClosed: true
    modalExportButton:
      text: Exporteer
    exportradio:
      options:
        - id: checkbox-3
          text: XML (De tekst zal worden geleverd in een .xml-bestand)
          name: exportopties
          modifier: exporteren-xml-optie
          value: rbXml
          checked: checked
        - id: checkbox-4
          text: TXT (De tekst zal worden geleverd in een .txt-bestand)
          name: exportopties
          value: rbTxt
        - id: checkbox-5
          text: RTF (Maak deze keuze als u de tekst wilt (her)gebruiken in een tekstverwerkingsprogramma)
          name: exportopties
          value: rbRtf
    exportradio2:
      options:
        - id: rbZonderAfbeeldingen
          text: Tekst zonder afbeeldingen exporteren
          name: exportopties2
          value: rbZonderAfbeeldingen
          checked: checked
        - id: rbMetAfbeeldingen
          text: Tekst met afbeeldingen exporteren
          name: exportopties2
          value: rbMetAfbeeldingen
  counter1:
    modifier: article__header--law--part
    useTitle: true
    titleTag: h2
    counter: Deel 1. Algemene bepalingen
    relationsAmount: 2
    export: true
    print: true
    compare: true
    version: true
    permalink: true
    relation: true
  counter2:
    modifier: article__header--law--chapter
    useTitle: true
    titleTag: h3
    counter: Hoofdstuk 1.1. Begripsbepalingen
    relationsAmount: 2
    export: true
    print: true
    compare: true
    version: true
    permalink: true
    relation: true
  counter3:
    useTitle: true
    titleTag: h3
    counter: Artikel 1.1
    relationsAmount: 1
    export: true
    print: true
    compare: true
    version: true
    permalink: true
    relation: true
