---
title: BWB - EU Richtlijnen zoeken
label: BWB - EU Richtlijnen zoeken
status: ready
context:
  headerContext:
    file: logo.svg
    alt: Overheid.nl logo
    youAreHere:
    - text: Wettenbank
    navLinks:
      - url: '#'
        text: Eenvoudig zoeken
      - url: '#'
        text: Uitgebreid zoeken
      - url: '#'
        text: Zoeken in EU-richtlijnen
        className: is-active
  breadcrumb:
    title: "U bent hier:"
    breadcrumb:
      - text: Zoeken op EU-richtlijn
  tt1:
    id: 1
    label: Help?
    content: U zoekt hier op het nummer van de richtlijn bestaande uit vier cijfers van het jaartal en maximaal vier cijfers van het nummer.
  tt2:
    id: 2
    label: Help?
    content: "Vul het gehele nummer (inclusief serie) van de vindplaats publicatieblad EU in en/of de bijbehorende publicatiedatum. Let op dat na de C of een L een spatie moet worden ingevuld. Voorbeeld: L 63/9 - 01-03-2008."
  tt3:
    id: 3
    label: Help?
    content: U zoekt hier op woord(en) in de citeertitel en het opschrift van de richtlijnen.
  tt4:
    id: 4
    label: Help?
    content: Toon uitsluitend regelingen die enkel op Bonaire, Sint Eustatius en Saba van toepassing zijn.
  tt45:
    id: 45
    label: Help?
    content: U kunt hier zoeken op een of meer woorden die voorkomen in de titel of in de tekst. Wanneer u 'Exact zoeken' uitvinkt, dan zoekt u ook op spellingsvarianten en woordsamenstellingen, e.d.
  tt5:
    id: 5
    label: Help?
    content: U zoekt hier op woord(en) in de citeertitel en het opschrift van de regelingen. U kunt ook populaire benamingen invoeren, zoals 'Flexwet'. Wilt u zoeken op de afkorting of op de volledige regelingtitel vink dan het betreffende vakje aan.
  tt6:
    id: 6
    label: Help?
    content: "U zoekt hier op woord(en) in de tekst van de regelingen. Als u wilt dat meerdere woorden voorkomen in de tekst, gebruikt u de EN-operator, bijv. ‘gezondheid EN veiligheid’. Als u wilt dat tenminste één van de woorden voorkomt in de tekst, gebruikt u de OF-operator, bijv. ‘gezondheid OF veiligheid’. Indien u ook op woordsamenstellingen wilt zoeken, dan kunt u gebruik maken van een '*'. Bijvoorbeeld met de zoekterm: ‘milieu*’, vindt u ook ‘milieuvergunning’ en ‘milieuplan’."
  tt7:
    id: 7
    label: Help?
    content: U kunt zoeken op alle voorkomende artikelnummers, zoals “1”, “1.1”, “1:1”.
  tt8:
    id: 8
    label: Help?
    content: U kunt zoeken in de regelingen zoals geldend op de datum vandaag (standaard), of een eerdere datum. Regelingen die materieel zijn uitgewerkt worden standaard niet doorzocht, tenzij u het vakje aanvinkt.
  tt9:
    id: 9
    label: Help?
    content: Regelingen die niet zijn ingetrokken of vervallen maar feitelijk geen werking meer hebben, worden standaard niet doorzocht. Wilt u dit wel, vink dan dit vakje aan.
  inputtext1:
    id: 1432
    fieldLabel: Jaar
    fieldVisibility: false
    fieldInstruction:
    fieldPlaceholder: 'jjjj'
    modifier: input--small
  inputtext2:
    id: 1433
    fieldLabel: Nummer
    fieldVisibility: false
    fieldInstruction:
    fieldPlaceholder: 'nnnn'
    modifier: input--small
  inputtext3:
    id: 1434
    fieldLabel: EU-publicatieblad
    fieldVisibility: false
    fieldInstruction:
    fieldPlaceholder: 'Bijv: L 63/9'
    modifier: input--small
  datepickerPublicatieblad:
    id: 1
    fieldLabel: Datum
    fieldInstruction:
    fieldPlaceholder: 'dd-mm-yyyy'
    configDateFormat: 'dd-mm-yy'
    debug: false
