---
title: BWB - Regeling WTI
label: BWB - Regeling WTI
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
    navLinks:
      - url: '#'
        text: Eenvoudig zoeken
        className: is-active
      - url: '#'
        text: Uitgebreid zoeken
      - url: '#'
        text: Zoeken in EU-richtlijnen
    youAreHere:
      - text: Wettenbank
  breadcrumb:
    title: "U bent hier:"
    breadcrumb:
      - text: Zoeken
        url: '#'
      - text: Zoekresultaten
        url: '#'
      - text: Regeling
  sidebar:
    modifier: list--facet
    heading: OfficiÃ«le bekendmakingen
    items:
      - content: <a href="#">Veelgestelde vragen</a>
  pageactions:
    title: ''
    intro: ''
    modifier: browse--icons
    items:
      - link: '#'
        text: downloaden
        icon: icon-download-black.svg
      - link: '#'
        text: printen
        icon: icon-print.svg
        actionPrint: true
  well:
    text: appel
  modalCompare:
    modalId: popupvergelijken
    initClosed: true
    closeButton: sluiten
    buttonModifier: wti-compare
  footnote:
    customlist: false
    text: Opmerkingen
    notes:
      - id: 1
        note: Tekstplaatsing met vernummering
      - id: 2
        note: Tekstplaatsing met vernummering
