---
title: BWB - EU Richtlijnen zoekresultaten
label: BWB - EU Richtlijnen zoekresultaten
status: ready
context:
  headerContext:
    file: logo.svg
    alt: Overheid.nl logo
    youAreHere:
    - text: Wettenbank
    navLinks:
      - url: '#'
        text: Eenvoudig zoeken
      - url: '#'
        text: Uitgebreid zoeken
      - url: '#'
        text: Zoeken in EU-richtlijnen
        className: is-active
  breadcrumb:
    title: "U bent hier:"
    breadcrumb:
      - text: Zoeken op EU-richtlijn
        url: '#'
      - text: Zoekresultaten
  pagination:
    title: Resultaat pagina's
    hLevel: 2
  resultlist:
    items:
      - title: RICHTLIJN 2009/116/EG VAN DE RAAD van 25 juni 2009 houdende wijziging van Richtlijn 91/414/EEG teneinde de paraffineoliën CAS-nummer 64742-46-7, CAS-nummer 72623-86-0 en CAS-nummer 97862-82-3 op te nemen als werkzame stoffen
        href: '#'
        labelSecondair: Richtlijn geïmplementeerd
        labelSecondairType: warning
      - title: GEDELEGEERDE RICHTLIJN 2014/14/EU van de Commissie van 18 oktober 2013 tot wijziging, met het oog op aanpassing aan de technische vooruitgang, van bijlage III bij Richtlijn 2011/65/EU van het Europees Parlement en de Raad wat betreft een vrijstelling voor 3,5 mg kwik per lamp in compacte fluorescentielampen met enkelvoudige lampvoet voor algemene verlichtingsdoeleinden < 30 W met een levensduur van ten minste 20 000 branduren
        href: '#'
        labelSecondair: Richtlijn geïmplementeerd
        labelSecondairType: warning
      - title: RICHTLIJN 2009/137/EG VAN DE COMMISSIE van 10 november 2009 tot wijziging van Richtlijn 2004/22/EG van het Europees Parlement en de Raad betreffende meetinstrumenten met betrekking tot het misbruiken van maximaal toelaatbare fouten voor wat betreft de instrumentspecifieke bijlagen MI-001 tot en met MI-005
        href: '#'
        labelSecondair: Richtlijn geïmplementeerd
        labelSecondairType: warning
  pageactions:
    items:
      - link: '#'
        text: printen
        icon: icon-print.svg
        title: Afdrukken
