---
title: BWB - Zoekresultaten
label: BWB - Zoekresultaten
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
    youAreHere:
      - text: Wettenbank
    navLinks:
      - url: '#'
        text: Eenvoudig zoeken
      - url: '#'
        text: Uitgebreid zoeken
        className: is-active
      - url: '#'
        text: Zoeken in EU-richtlijnen
  breadcrumb:
    title: "U bent hier:"
    breadcrumb:
      - text: Uitgebreid zoeken
        url: '#'
      - text: Zoekresultaten
  spoedpublicatiemelding:
    modifier: alert--info
    text: Lorem ipsum dolor sit amet, consectetur adipisicing elit.
  actieblok:
    title: 'Acties'
    intro: ''
    modifier: browse--icons
    items:
      - link: '#'
        text: Alles openklappen
        icon: icon-plus.svg
      - link: '#'
        text: Alles dichtklappen
        icon: icon-minus.svg
      - link: '#'
        text: Alles uitvinken
        icon: icon-uncheckall.svg
        id: unmarkallAnchor
      - link: '#'
        text: Toon aanvinkte elementen
        icon: icon-arrow-right.svg
  pageactions:
    items:
      - link: '#'
        text: downloaden
        icon: icon-download-black.svg
        title: Opslaan als RTF-bestand
      - link: '#'
        text: printen
        icon: icon-print.svg
        title: Afdrukken
  resultlist:
    item1:
      title: Aanbestedingswet 2012
      href: '#'
      amountResults: (430 artikelen)
      hiddenInputs:
        - id:
          class: data-id
          value: http://wetten.overheid.nl/id/BWBR0032203/2019-04-18/0
        - id:
          class: data-nr
          value: 0
        - id:
          class: locationurl
          value: https://wetten.overheid.nl/uitgebreid_zoeken/zoekresultaat/rs/2,3,4,5,7/titelf/1/tekstf/1/wti/0/artnrb/0/d/17-02-2021/zd/17-02-2021/dx/0/ds/0/dt/1/db/1
      collapsible:
        id: 3
        heading: 605 relevante elementen
        modifier: collapsible--small
    item2:
      title: Aanbestedingswet op defensie- en veiligheidsgebied
      href: '#'
      labelsSecondair:
        - labelSecondair: Regeling materieel uitgewerkt per 08-07-2022
          labelSecondairType: warning
      amountResults: (173 artikelen)
      hiddenInputs:
        - id:
          class: data-id
          value: http://wetten.overheid.nl/id/BWBR0032898/2019-04-18/0
        - id:
          class: data-nr
          value: 1
        - id:
          class: locationurl
          value: https://wetten.overheid.nl/uitgebreid_zoeken/zoekresultaat/rs/2,3,4,5,7/titelf/1/tekstf/1/wti/0/artnrb/0/d/17-02-2021/zd/17-02-2021/dx/0/ds/0/dt/1/db/1
      collapsible:
        id: 23
        heading: 247 relevante elementen
        modifier: collapsible--small
  resultlist2:
    item1:
      title: "Aanhangsel I: Internationale Arbeidsorganisatie bij het Verdrag nopens de voorrechten en immuniteiten van de gespecialiseerde organisaties"
      href: '#'
      labelsSecondair:
        - labelSecondair: Authentiek-EN, Vertaling-NL
          labelSecondairType: warning
        - labelSecondair: 'Datum totstandkoming: 10-07-1948'
          labelSecondairType: warning
        - labelSecondair: 'Plaats totstandkoming: San Francisco'
          labelSecondairType: warning
      collapsible:
        id: 33
        heading: 7 relevante elementen
        modifier: collapsible--small
      hiddenInputs:
        - id:
          class: data-id
          value: http://wetten.overheid.nl/id/BWBV0005592/1948-12-02/0
        - id:
          class: data-nr
          value: 0
        - id:
          class: locationurl
          value: https://wetten.overheid.nl/uitgebreid_zoeken/zoekresultaat/titelf/1/tekstf/1/wti/0/artnrb/0/d/17-02-2021/zd/17-02-2021/dx/0/ds/0/dt/1/db/1
  pagination:
    title: Resultaat pagina's
    hLevel: 2
  sort:
    options:
      - label: Titel
        href: '#'
      - label: Soort
        href: '#'
        active: is-active
