title: Disclaimer
status: prototype
context:
  id: 1
  content: <p>Staatsblad, Staatscourant en Tractatenblad worden met ingang van 1 juli 2009 als pdf-bestanden uitgegeven. De hier aangeboden pdf-bestanden van deze bladen vormen de formele bekendmakingen in de zin van de Grondwet. Voor publicaties van vóór deze datum geldt dat alleen de in papieren vorm uitgegeven bladen formele status hebben; de hier aangeboden elektronische versies daarvan worden bij wijze van service aangeboden.</p>
