title: Nav
label: Navigatie (sidebar)
status: ready
default: Nav
context:
  id: 1
  items:
    - title: Basisgegevens
      active: true
      sub: true
      subItems:
        - stitle: Algemeen
        - stitle: Koninkrijk
          sactive: true
        - stitle: Partijen
        - stitle: Uitbreidingen
    - title: Voorbehouden, verklaringen en bezwaren
    - title: Wijzigingen

