---
label: IC - Reageren
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
    language: true
    skipLinks:
      - url: '#content'
        text: Direct naar content
  navConsultatieContext:
    id: 3
    items:
    - title: Consultatie
      sub: true
      active: true
      sactive: true
      subItems:
      - stitle: In het kort
        href: "/components/preview/templates-ic2-contentpage#section-1"
      - stitle: Consultatiegegevens
        href: "/components/preview/templates-ic2-contentpage#sectie-consultatiegegevens"
      - stitle: Voor wie is dit belangrijk
        href: "/components/preview/templates-ic2-contentpage#sectie-watisbelangrijk"
      - stitle: Wat verandert deze wet?
        href: "/components/preview/templates-ic2-contentpage#sectie-watveranderdewet"
      - stitle: Praktijkvoorbeelden
        href: "/components/preview/templates-ic2-contentpage#sectie-praktijkvoorbeelden"
      - stitle: Waar kunt u op reageren?
        href: "/components/preview/templates-ic2-contentpage#sectie-waarkuntuopreageren"
      - stitle: Ondersteunende documenten
        href: "/components/preview/templates-ic2-contentpage#sectie-ondersteunendedocumenten"
  navReagerenContext:
    id: 4
    items:
    - title: Reageren
      sub: true
      subItems:
      - stitle: Reageren
        href: "#"
      - stitle: Reacties
        href: "#"
  listDelen:
    items:
        - content: <a href="https://www.facebook.com/sharer/sharer.php?u=#http://www.internetconsultaties.nl/" class="icon icon--facebook">Facebook</a>
        - content: <a href="https://www.linkedin.com/shareArticle?mini=true&url=http://www.internetconsultaties.nl/&title=titel&summary=summary&source=internetconsultaties" class="icon icon--linkedin">LinkedIn</a>
        - content: <a href="http://twitter.com/share?text=omschrijving&url=http://www.internetconsultaties.nl/&hashtags=hashtag1" class="icon icon--twitter">Twitter</a>
        - content: <a href="#" class="icon icon--instagram">Instagram</a>
        - content: <a href="mailto:?subject=onderwerp&amp;body=omschrijving" class="icon icon--mail">E-mail</a>
        - content: <a href="whatsapp://send?text=omschrijving" class="icon icon--whatsapp">Whatsapp</a>
  pageactions:
    items:
    - link: '#'
      text: Downloaden
      icon: icon-download.svg
    - link: '#'
      text: Printen
      icon: icon-print-blue.svg
  label1:
    text: Consultatie gesloten
    modifier: label--large label--danger
  label2:
    text: Onderwijs
  linkAbonneer:
    text: Abonneer op nieuwe consultaties
  linkReageer:
    text: Reageer op deze consultatie
  listCheck:
    items:
      - content: Bent u blij, boos of verdrietig om dit voorstel? Schrijf dan duidelijk op waaróm dat zo is
      - content: Verwijs naar onderdelen van de wet door deze stukken te kopiëren in uw antwoord
      - content: Onderbouw je mening of idee met feiten
  reactiesoort:
    options:
      - id: 1
        name: subject
        checked: checked
        text: Vrije invoer
        linkedto: 2
      - id: 2
        text: Vragen beantwoorden
        name: subject
        linkedto: 3
      - id: 3
        text: Document uploaden
        name: subject
        linkedto: 4
  textareaContext:
    id: 543
    fieldLabel: Uw reactie
    fieldLabelModifier: form__label--accent
    fieldPlaceholder: Schrijf uw reactie
  textareaContext2:
    id: 544
    fieldLabel: Vraag 1
    fieldLabelModifier: form__label--accent
    fieldPlaceholder: Schrijf uw reactie
  textareaContext3:
    id: 545
    fieldLabel: Vraag 2
    fieldLabelModifier: form__label--accent
    fieldPlaceholder: Schrijf uw reactie
  buttonSubmit:
    text: Ga verder naar persoonsgegevens
    button: true
    inputButton: true
    type: submit
    modifier: button--primary
