---
label: Input text
status: ready
context:
  id: 1
  type: text
  fieldLabel: Op nummer zoeken
  fieldInstruction:
  fieldPlaceholder: 'Bijv: BK001'
variants:
  - name: Password
    label: Input password
    context:
      modifier: input--postalcode input--small
      id: 1
      type: password
      fieldLabel: password
      fieldInstruction:
      fieldPlaceholder: 'Password'
  - name: Number
    label: Input Number
    context:
      modifier: input--postalcode input--small
      id: 1
      type: number
      fieldLabel: number
      fieldInstruction:
      fieldPlaceholder: 'number'
  - name: Email
    label: Input Email
    context:
      modifier: input--email input--small
      id: 1
      type: email
      fieldLabel: email
      fieldInstruction:
      fieldPlaceholder: 'email'
  - name: URL
    label: Input URL
    context:
      modifier: input--url input--small
      id: 1
      type: url
      fieldLabel: URL
      fieldInstruction:
      fieldPlaceholder: 'URL'
  - name: Postal code
    label: Input Postcode
    context:
      type: text
      modifier: input--postalcode input--small
      id: 1
      fieldLabel: Postcode
      fieldInstruction:
      fieldPlaceholder: 'Bijv: 2282LL'
  - name: Tel
    label: Input Tel
    context:
      type: tel
      modifier: input--tel
      id: 1
      fieldLabel: Telefoonnummer
      fieldInstruction:
      fieldPlaceholder: 'Bijv: 061234567879'
  - name: Medium
    label: Groot
    context:
      type: text
      modifier: input-text--medium
      id: 1
      fieldPlaceholder: 'Placeholder'
  - name: Search
    label: Zoeken
    context:
      modifier: input-text--search
      id: 1
      type: text
      fieldLabel: Postcode
      fieldInstruction:
      fieldPlaceholder: 'Wat zoek je precies?'
      remove: true
  - name: Search medium
    label: Zoeken (groot)
    context:
      type: text
      modifier: input-text--searchmedium
      id: 1
      fieldLabel: Postcode
      fieldInstruction:
      fieldPlaceholder: 'Wat zoek je precies?'
      remove: true
  - name: Prefix
    label: Prefix
    context:
      modifier:
      type: text
      id: 1
      fieldLabel: Postcode
      fieldInstruction:
      fieldPlaceholder:
      prefix: true
      prefixLabel: https://www.overheid.nl/
  - name: With remove
    label: met Remove
    context:
      remove: true
  - name: Error
    label: met Foutmelding
    context:
      value: uwnaam@overheidnl
      error: true
      errorMessage: Ongeldig e-mailadres
