---
label: PLOOI - Searchresults
status: prototype
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
  voorschriftenContext:
    moreless: true
    options:
    - id: checkbox-20
      text: Aanwijzingsbesluit
      name: onderwerp
    - id: checkbox-20
      text: Agenda en notulen
      name: onderwerp
    - id: checkbox-20
      text: Belastingbesluit
      name: onderwerp
    - id: checkbox-20
      text: Besluitenlijst
      name: onderwerp
    - id: checkbox-20
      text: Collectevergunning
      name: onderwerp
    - id: checkbox-20
      text: Delegatiebesluit
      name: onderwerp
    - id: checkbox-20
      text: Gemeenschappelijke regelingen
      name: onderwerp
    - id: checkbox-20
      text: Kansspelvergunning
      name: onderwerp
    - id: checkbox-20
      text: Loterijvergunning
      name: onderwerp
    - id: checkbox-20
      text: Milieu-informatie
      name: onderwerp
    - id: checkbox-20
      text: Milieuverordening
      name: onderwerp
    - id: checkbox-20
      text: Optochtvergunning
      name: onderwerp
    - id: checkbox-20
      text: Peilbesluit
      name: onderwerp
    - id: checkbox-20
      text: Register kinderopvang
      name: onderwerp
    - id: checkbox-20
      text: Stedelijk waterplan
      name: onderwerp
    - id: checkbox-20
      text: Streekplan
      name: onderwerp
    - id: checkbox-20
      text: Stroomgebiedsvisie
      name: onderwerp
    - id: checkbox-20
      text: Structuurvisie
      name: onderwerp
    - id: checkbox-20
      text: Vaarvergunning
      name: onderwerp
    - id: checkbox-20
      text: Ventvergunning
      name: onderwerp
    - id: checkbox-20
      text: Vervoer gevaarlijke stoffen vergunning
      name: onderwerp
    - id: checkbox-20
      text: Verordeningen en reglementen
      name: onderwerp
    - id: checkbox-20
      text: Waterbeheersplan
  bestemmingContext:
    moreless: true
    options:
    - id: checkbox-20
      text: Bestemmingsplan
      name: onderwerp
    - id: checkbox-20
      text: Voorbereidingsbesluit
      name: onderwerp
  voorlichtingContext:
    moreless: true
    options:
    - id: checkbox-20
      text: Aankondiging
      name: onderwerp
    - id: checkbox-20
      text: Huisafval
      name: onderwerp
    - id: checkbox-20
      text: Inspraak
      name: onderwerp
    - id: checkbox-20
      text: Mededelingen
      name: onderwerp
    - id: checkbox-20
      text: Meldingen
      name: onderwerp
    - id: checkbox-20
      text: Openingstijden
      name: onderwerp
    - id: checkbox-20
      text: Overig
      name: onderwerp
    - id: checkbox-20
      text: Rectificatie
      name: onderwerp
    - id: checkbox-20
      text: Verkiezingen
      name: onderwerp
  onderwerpContext:
    moreless: true
    options:
    - id: checkbox-20
      text: Alle
      name: onderwerp
    - id: checkbox-20
      text: Vandaag
      name: onderwerp
    - id: checkbox-20
      text: Afgelopen week
      name: onderwerp
    - id: checkbox-20
      text: Afgelopen maand
      name: onderwerp
    - id: checkbox-20
      text: Afgelopen 3 maanden
      name: onderwerp
    - id: checkbox-20
      text: Zelf een periode kiezen
      name: onderwerp
  publicatiedatumContext:
    moreless: true
    options:
    - id: radio-1
      text: Vandaag
      name: publicatie
    - id: radio-2
      text: Afgelopen week
      name: publicatie
    - id: radio-3
      text: Afgelopen maand
      name: publicatie
    - id: radio-4
      text: Afgelopen 2 maanden
      name: publicatie
      disabled: disabled
    - id: radio-5
      text: Zelf een periode kiezen
      name: publicatie
  gebiedContext:
    moreless: true
    options:
    - id: radio-1
      text: Berichten rond mijn adres
      name: publicatie
    - id: radio-2
      text: Berichten in mijn gemeente
      name: publicatie
  resultmodalContext:
    modifier: result--list--wide
    items:
    - title: Aangevraagde evenementenvergunningen 2018
      headerimg: https://via.placeholder.com/720x280.png?text=Kaart+met+marker
      titleHeader: h2
      text: 4 september 2018 -  Aangevraagde evenementenvergunningen 2018
      buttons:
        - button: Bekijk publicatie
          type: primary
        - button: Bekijk op kaart
          type: primary
          action: modal-4
          modal: true
  sortContext:
    modifier:
    amountPerPageFilter: true
    columns: true
    options:
    - label: Datum
      value: value
      active: is-active
    - label: Titel
      value: value
  inputsubmitContext:
    label: Verfijn uw zoekopdracht
    showLabel: false
    placeholder: Verfijn uw zoekopdracht
    button: Zoek
    modifier: input-text--search
  resultsContext:
    modifier: result--list--wide
    items:
    - title: Voortgangsrapportage CTIVD over de werking Wiv2017
      titleHeader: h2
      label: Nieuw vandaag
      text: Het rapport bevat de bevindingen van de Commissie van Toezicht op de Inlichtingen- en Veiligheidsdiensten inzake de werking van de Wet op de inlichtingen en veiligheidsdiensten 2017
      share: false
      buttons:
        - button: Bekijk publicatie
          type: secendary
      metadata:
        - value: Onderzoeksrapport
        - value: Ministerie van Justitie en Veiligheid
        - value: Beschikbaar sinds 04-12-2018
      linklist: true
      linklistLimit: true
      linklistItems:
        - link: Rijksoverheid.nl
          txt: (gepubliceerd op 07-07-2016 | XML)
        - link: Overheid.nl
          txt: (gepubliceerd op 06-07-2016 | PDF)
        - link: Rijksoverheid.nl
          txt: (gepubliceerd op 07-07-2016 | XML)
    - title: AppelAfdeling 1.2.1. Algemene bepaling voor het sluiten van schriftelijke overeenkomsten onder bezwarende titel voor het verrichten van werken, leveringen of dienstent
      titleHeader: h2
      label: Nieuw vandaag
      text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus, obcaecati! Aperiam quasi debitis exercitationem ducimus! Eligendi, iusto, ut! Tempore ab sit eveniet fugit officia minus incidunt atque facilis saepe at!
      share: true
      buttons:
        - button: Bekijk publicatie
          type: primary
        - button: Bekijk op kaart
          type: secendary
    - title: AppelAfdeling 1.2.1. Algemene bepaling voor het sluiten van schriftelijke overeenkomsten onder bezwarende titel voor het verrichten van werken, leveringen of dienstent
      titleHeader: h2
      label: Nieuw vandaag
      text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus, obcaecati! Aperiam quasi debitis exercitationem ducimus! Eligendi, iusto, ut! Tempore ab sit eveniet fugit officia minus incidunt atque facilis saepe at!
      share: true
      buttons:
        - button: Bekijk publicatie
          type: primary
        - button: Bekijk op kaart
          type: secendary
  inputSearchContext:
    modifier: input-text--searchmedium
    id: 1
    fieldLabel: Postcode
    fieldLabelVisible: false
    fieldInstruction:
    fieldPlaceholder: Verfijn op zoekwoord
    remove: true

  inputsubmitSearchSaveContext:
    label: Uw e-mailadres
    showLabel: true
    placeholder: Uw e-mailadres
    button: Bevestigen
  buttonswitchContext:
    text: banner
    buttons:
      - label: Kaart
        active: true
        icon: marker
      - label: Lijst
        active: false
        icon: hamburger
  selectedfilterContext:
    items:
      - label: Gezocht op
        value: leveringen
        url: "#"
      - label: Bouwvergunning
        url: "#"
      - label: APV vergunning
        url: "#"
  subselectionContext:
    linkText: Selecteer organisatie(s)
    id: 1
    modalTitle: Selecteer organisatie(s)
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    searchFilter: true
    type: span
    Options:
      - Option: 1
        id: 1
        title: Spanje
        short: Spanje
      - Option: 2
        id: 2
        title: Griekenland
        short: Griekenland
      - Option: 3
        id: 3
        title: Nederland
        short: Nederland
  subselectionThemaContext:
    linkText: Selecteer thema(s)
    id: 12
    modalTitle: Selecteer thema(s)
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    searchFilter: true
    type: span
    triggerSubmit: true
    Options:
      - Option: 4
        id: 4
        title: Spanje
        short: Spanje
      - Option: 5
        id: 5
        title: Griekenland
        short: Griekenland
      - Option: 6
        id: 6
        title: Nederland
        short: Nederland
  subselectionInfoContext:
    linkText: Selecteer informatiesoort(en)
    id: 13
    modalTitle: Selecteer informatiesoort(en)
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    searchFilter: true
    type: span
    Options:
      - Option: 465
        id: 465
        title: Spanje
        short: Spanje
      - Option: 565
        id: 565
        title: Griekenland
        short: Griekenland
      - Option: 665
        id: 665
        title: Nederland
        short: Nederland





