---
label: PLOOI - Homepage uitgebreid
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
    language: true
  jumbotronContext:
    heading: Documenten van Nederlandse overheden actief openbaar
    hstyle: h2
    subheading: Overheidsdocumenten
    intro: In overheidsdocumenten zoekt u naar documenten actief openbaar gemaakt door alle Nederlandse bestuursinstanties volgens Wet open overheid.
    size: medium
    centered: true
    inputsubmitContext:
      button: Zoek verdagen
      placeholder: Vul hier uw zoekwoord(en) in
    inputZoekwoord:
      fieldPlaceholder: Zoekwoord of zinsdeel
      fieldLabel: Zoek naar documenten
      fieldLabelVisible: true
      labelmodifier: medium
      modifier: input-text--searchmedium
    searchcheckbox:
      options:
        - id: checkbox-19874
          text: Zoek alleen in titels
          name: searchcr
    subselectionOnderwerpContext:
      linkText: Selecteer onderwerp(en)
      id: 23
      modalTitle: Selecteer onderwerp(en)
      fieldLabel: fieldLabel
      fieldInstruction:
      fieldPlaceholder: 'Bijv: 0612345678'
      searchFilter: true
      type: span
      Options:
        - Option: 1
          id: 123
          title: Spanje
          short: Spanje
        - Option: 2
          id: 223
          title: Griekenland
          short: Griekenland
        - Option: 3
          id: 323
          title: Nederland
          short: Nederland
    radioContext1:
      options:
        - id: 1
          text: Zoek alleen in titels
          name: zoek
          checked: checked
    radioContext2:
      options:
        - id: 2
          text: Zoek in de hele tekst
          name: zoek
    subselectionContext:
      linkText: Selecteer organisatie(s)
      id: 1
      modalTitle: Selecteer organisatie(s)
      fieldLabel: fieldLabel
      fieldInstruction:
      fieldPlaceholder: 'Bijv: 0612345678'
      searchFilter: true
      type: span
      Options:
        - Option: 1
          id: 134
          title: Spanje
          short: Spanje
        - Option: 2
          id: 234
          title: Griekenland
          short: Griekenland
        - Option: 3
          id: 334
          title: Nederland
          short: Nederland
    subselectionThemaContext:
      linkText: Selecteer thema(s)
      id: 16
      modalTitle: Selecteer thema(s)
      fieldLabel: fieldLabel
      fieldInstruction:
      fieldPlaceholder: 'Bijv: 0612345678'
      type: span
      searchFilter: true
      searchFilterPlaceholder: Typ hier uw thema
      OptionsLabel: Thema 1
      OptionsIsCheckAll: true
      OptionsIsCheckAllID: 1
      Options:
        - Option: 4
          id: 4
          title: Thema 1 Sub 1
          short: Thema 1 Sub 1
        - Option: 5
          id: 5
          title: Thema 1 Sub 2
          short: Thema 1 Sub 2
        - Option: 6
          id: 6
          title: Thema 1 Sub 3
          short: Thema 1 Sub 3
        - Option: 6
          id: 634322
          title: Thema 1 Sub 4
          short: Thema 1 Sub 4
      Options2Label: Thema 2
      Options2IsCheckAll: true
      Options2IsCheckAllID: 2
      Options2:
        - Option: 7
          id: 7
          title: Thema 2 Sub 1
          short: Thema 2 Sub 1
        - Option: 8
          id: 8
          title: Thema 2 Sub 2
          short: Thema 2 Sub 2
    subselectionInfoContext:
      linkText: Selecteer informatiesoort(en)
      id: 122
      modalTitle: Selecteer informatiesoort(en)
      fieldLabel: fieldLabel
      fieldInstruction:
      fieldPlaceholder: 'Bijv: 0612345678'
      searchFilter: true
      type: span
      Options:
        - Option: 4
          id: 456
          title: Spanje
          short: Spanje
        - Option: 5
          id: 556
          title: Griekenland
          short: Griekenland
        - Option: 6
          id: 656
          title: Nederland
          short: Nederland
    onderwerpContext:
      moreless: true
      searchFilter: true
      options:
      - id: checkbox-2220
        text: Alle
        name: onderwerp
        checked: checked
      - id: checkbox-220
        text: Vandaag
        name: onderwerp
      - id: checkbox-201
        text: Afgelopen week
        name: onderwerp
      - id: checkbox-202
        text: Afgelopen maand
        name: onderwerp
      - id: checkbox-203
        text: Afgelopen 3 maanden
        name: onderwerp
      - id: checkbox-204
        text: Zelf een periode kiezen
        name: onderwerp
    tt1Context:
      id: 112
    tt2Context:
      id: 113
    tt3Context:
      id: 114
    tt4Context:
      id: 115

