---
label: Filtersearch results
status: prototype
context:
  id: 1
  gemeentenContext:
    options:
    - id: checkbox-20
      text: Haarlem
      name: onderwerp
    - id: checkbox-21
      text: Haarlemmermeer
      name: onderwerp
    - id: checkbox-22
      text: Halderberge
      name: onderwerp
    - id: checkbox-22
      text: Hardenberg
      name: onderwerp
    - id: checkbox-22
      text: Hattem
      name: onderwerp
    - id: checkbox-22
      text: Heerenveen
      name: onderwerp
    - id: checkbox-22
      text: Helmond
      name: onderwerp
  selectedfilterContext:
    items:
      - label: "Gemeenten: Den Haag"
      - label: "Ministeries: Ministerie van Binnenlandse Zaken"
