name: DS - Componenten
label: DS - Componenten
context:
  header:
    nav: false
  breadcrumb:
    last: Componenten
    breadcrumbs:
    - label: Overheid.nl
      path: 'test'
    - label: Design system
      path: 'test'
  navMenuContext:
    items:
    - title: Design system
      active: true
      href: templates-ds---index.html
      sub: true
      subItems:
        - stitle: Rationale
          href: templates-ds---rationale.html
        - stitle: Toelichting
          href: templates-ds---toelichting.html
        - stitle: Ontwerpprincipes
          href: templates-ds---ontwerpprincipes.html
        - stitle: Componenten
          href: templates-ds---componenten.html
          sactive: true
        - stitle: Content
          href: templates-ds---content.html
  jumbotronContext:
    heading: Componenten
    h: h1
    subheading: Design system
    intro: Op deze pagina's vind je een overzicht van de beschikbare componenten waarmee websites kunnen worden opgebouwd.
  inputDefault:
    type: email
  inputHasError:
    type: email
    haserror: true
    describedby: 12341242
    value: koopkoop.overheid.nl
  inputIsDisabled:
    type: email
    disabled: true
    fieldPlaceholder: Ingevulde waarde
  navComponentsContext:
    items:
    - title: Components
      active: false
      sub: true
      anker: true
      subItems:
        - stitle: Accordion
          href: accordion
        - stitle: Actieblok
          href: actieblok
        - stitle: Adres
          href: adres
        - stitle: Alert
          href: alert
        - stitle: Artikel hoofd
          href: artikelhoofd
        - stitle: A-Z Lijst
          href: azlijst
        - stitle: Banner
          href: banner
        - stitle: Blok
          href: blok
        - stitle: Blockquote
          href: blockquote
        - stitle: Bronlijst
          href: bronlijst
        - stitle: Browse
          href: browse
        - stitle: Buttons
          href: buttons
        - stitle: Buttongroup
          href: buttongroup
        - stitle: CopyData
          href: copydata
        - stitle: Characteristics
          href: characteristics
        - stitle: Collapsible
          href: collapsible
        - stitle: Definitionlist
          href: definitionlist
        - stitle: Del / Ins
          href: delins
        - stitle: Documentbanner
          href: documentbanner
        - stitle: Facet
          href: facet
        - stitle: Figure
          href: figure
        - stitle: Grid & containers
          href: gridcontainers
        - stitle: Highlight
          href: highlight
        - stitle: Homepage blok
          href: homepageblok
        - stitle: Jumbotron
          href: jumbotron
        - stitle: Labels
          href: labels
        - stitle: Link
          href: link
        - stitle: Lists
          href: lists
        - stitle: Loader
          href: loader
        - stitle: Logo
          href: logo
        - stitle: Modal
          href: modal
        - stitle: Navigation
          href: navigation
        - stitle: OpenLayers
          href: openlayers
        - stitle: Pagina acties
          href: pageactions
        - stitle: Pagination
          href: pagination
        - stitle: Picture
          href: picture
        - stitle: Pre
          href: pre
        - stitle: Profiel
          href: profiel
        - stitle: Relevances
          href: relevances
        - stitle: Resultaten lijst
          href: resultlist
        - stitle: Skiplinks
          href: skiplinks
        - stitle: Sorteren
          href: sort
        - stitle: Stappen
          href: steps
        - stitle: Sub sup
          href: subsup
        - stitle: Tabel
          href: table
        - stitle: Tabel container
          href: table-container
        - stitle: Tabel topbar
          href: table-topbar
        - stitle: Tabs
          href: tabs
        - stitle: Tekst
          href: text
        - stitle: Thema blok
          href: themeblock
        - stitle: Toolbar
          href: toolbar
        - stitle: Topbar
          href: topbar
        - stitle: Treeview
          href: treeview
        - stitle: Video
          href: video
        - stitle: Voetnoot
          href: voetnoot
        - stitle: Well
          href: well
  navFormComponentsContext:
    items:
    - title: Formulieren
      active: false
      sub: true
      anker: true
      subItems:
        - stitle: Algemeen
          href: algemeen
        - stitle: Autocomplete
          href: autocomplete
        - stitle: Datumselectie
          href: datumselectie
        - stitle: Datepicker
          href: datepicker
        - stitle: Geselecteerde filter
          href: geselecteerdefilter
        - stitle: Input Checkbox
          href: inputcheckbox
        - stitle: Input File
          href: inputfile
        - stitle: Input Group
          href: inputgroup
        - stitle: Input InputSubmit
          href: inputinputsubmit
        - stitle: Input Radio
          href: inputradio
        - stitle: Input Text
          href: inputtekst
        - stitle: Select
          href: select
        - stitle: Select Multi
          href: selectmulti
        - stitle: Subselection
          href: subselection
        - stitle: Textarea
          href: textarea
        - stitle: Tooltip
          href: tooltip
  inputfile2:
    id: 09876567
  datepickerToday:
    id: 0876
  alertFixed:
    fixed: true
  subSel1:
    name: Default
    id: 1131312
    type: span
    linkText: Selecteer
    modalTitle: Selecteer ministeries
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    Options:
      - Option: 11123
        id: 1123
        title: Landbouw, Natuur en Voedselkwaliteit (lnv)
        short: lnv
        checked: checked
      - Option: 2123
        id: 2123
        title: Onderwijs, Cultuur en Wetenschap (ocw)
        short: ocw
      - Option: 3123
        id: 3123
        title: Sociale Zaken en Werkgelegenheid (szw)
        short: szw
  subSel2:
    name: Default
    id: 113
    type: span
    linkText: Selecteer onderwerp(en)
    modalTitle: Selecteer ministeries
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    Options:
      - Option: 1112323
        id: 112323
        title: Landbouw, Natuur en Voedselkwaliteit (lnv)
        short: lnv
      - Option: 212323
        id: 212323
        title: Onderwijs, Cultuur en Wetenschap (ocw)
        short: ocw
      - Option: 312323
        id: 312323
        title: Sociale Zaken en Werkgelegenheid (szw)
        short: szw
  profileLoggedin:
    id: 2765432
  profileLoggedin2:
    id: 2765431
