name: DS - Templates
label: DS - Templates
context:
  header:
    nav: false
  breadcrumb:
    last: Content
    breadcrumbs:
    - label: Overheid.nl
      path: 'test'
    - label: Design system
      path: 'test'
  navMenuContext:
    items:
    - title: Design system
      active: true
      href: templates-ds---index.html
      sub: true
      subItems:
        - stitle: Rationale
          href: templates-ds---rationale.html
        - stitle: Toelichting
          href: templates-ds---toelichting.html
        - stitle: Ontwerpprincipes
          href: templates-ds---ontwerpprincipes.html
        - stitle: Componenten
          href: templates-ds---componenten.html
        - stitle: Content
          href: templates-ds---content.html
  jumbotronContext:
    heading: Templates
    h: h1
    subheading: Design system
  navContentContext:
    items:
    - title: Content
      active: false
      sub: true
      anker: true
      subItems:
        - stitle: Home
          href: sectie-home
        - stitle: Landing
          href: sectie-landing
        - stitle: Uitgebreid zoeken
          href: sectie-uitgebreidzoeken
        - stitle: Zoekresultaten
          href: sectie-zoekresultaten
        - stitle: Detail
          href: sectie-detail
  alertInformatie:
    text: De 'landing' van een collectie bestaat altijd uit een aantal vaste elementen. De invulling van de 'collectie onderscheidend' is specifiek per collectie invulbaar. Momenteel is er nog geen duidelijke rationale achter de invulling hiervan en is er een geaccepteerde afwijking tussen de verschillende collecties.
  alertUZ:
    text: Uitgebreid zoeken heeft een afhankelijkheid met de rationale rondom 'zoeken'. Deze rationale zijn nog niet compleet waardoor er een afwijking is ontstaan in de toepassing. Dit is een geaccepteerde afwijking. Nieuwe toepassing van een uitgebreid zoeken template dient te worden gebaseerd op de nieuwe rationale.

