title: Artikel header wetten.nl
label: Artikel hoofd
context:
  useTitle: true
  titleTag: h3
  counter: Afdeling 1.2.1. Algemene bepaling voor het sluiten van schriftelijke overeenkomsten onder bezwarende titel voor het verrichten van werken, leveringen of diensten
  relationsAmount: 128
  activeFrom: Versie geldend per 01-04-2012
