title: Tr Homepage
label: Tr Homepage
status: ready
context:
  id: 1
  headerContext:
    metaLinks:
      - url: "#"
        text: MijnOverheid.nl
  breadcrumbContext:
    breadcrumb:
      last: Tuchtrecht
      items:
        - label: Home
  facelistContext:
    modifier: list--facet
    heading: Meer informatie
    headingType: h3
    items:
      - text: <a href="#">Instanties tuchtrecht</a>
  facelistContext2:
    modifier: list--facet
    heading: Acties
    headingType: h3
    items:
      - text: <a href="#">Afdrukken</a>
  actionblockContext:
    title: "Vrije beroepen"
    intro: ""
    items:
      - link: "#"
        text: Accountants (3)
        icon: icon-arrow-right.svg
      - link: "#"
        text: Advocaten (70)
        icon: icon-arrow-right.svg
      - link: "#"
        text: Diergeneeskundigen (0)
        icon: icon-arrow-right.svg
      - link: "#"
        text: Gerechtsdeurwaarders (45)
        icon: icon-arrow-right.svg
      - link: "#"
        text: Gezondheidszorg (0)
        icon: icon-arrow-right.svg
      - link: "#"
        text: Notarissen (0)
        icon: icon-arrow-right.svg
      - link: "#"
        text: Scheepvaart (0)
        icon: icon-arrow-right.svg
  actionblockContext2:
    title: "Producten"
    intro: ""
    items:
      - link: "#"
        text: Akkerbouw (3)
        icon: icon-arrow-right.svg
      - link: "#"
        text: Pluimvee en eieren (70)
        icon: icon-arrow-right.svg
      - link: "#"
        text: Vee en vlees (0)
        icon: icon-arrow-right.svg
