title: Wettenpocket Homepage
label: Wettenpocket Homepage
preview: "@preview.default"
context:
  headerContext:
    file: logo.svg
    alt: Overheid.nl logo
    navLinks:
      - url: '/templates-wp-homepage'
        className: 'is-active'
        text: Home
      - url: '#'
        text: Wettenpockets aanmaken
  navlistContext:
    modifier: 'list--linked list--unstyled'
    items:
      - text: <a href="templates-wp-search">Zoek wettenpockets</a>
      - text: <a href="templates-wp-overview">Recent gepubliceerde wettenpockets</a>
      - text: <a href="#">Veel gedownloade wettenpockets</a>
      - text: <a href="#">Veelgestelde vragen</a>
