title: Wettenpocket Overzichtspagina
label: Wettenpocket Overview
preview: "@preview.default"
status: ready
context:
  headerContext:
    file: logo.svg
    alt: Overheid.nl logo
    navLinks:
      - url: 'templates-wp-homepage'
        text: Home
      - url: '#'
        text: Wettenpockets aanmaken
  navlistContext:
    modifier: 'list--linked list--unstyled'
    items:
      - text: <a href="templates-wp-search">Zoek wettenpockets</a>
      - text: <a href="templates-wp-overview">Recent gepubliceerde wettenpockets</a>
      - text: <a href="#">Veel gedownloade wettenpockets</a>
      - text: <a href="#">Veelgestelde vragen</a>
  resultsContext:
    items:
    - title: Wettenpocket Wetboek van Strafrecht
      text: Automatisch gegenereerde pocket van wet- en regelgeving rond Wetboek van Strafrecht
      metadata:
        - value: "Datum: 21-11-2018"
        - value: "Onderwerp: Overig"
        - value: "Gepubliceerd door: KOOP"
    - title: Wettenpocket Warenwet
      text: Automatisch gegenereerde pocket van wet- en regelgeving rond Warenwet
      metadata:
        - value: "Datum: 21-11-2018"
        - value: "Onderwerp: Overig"
        - value: "Gepubliceerd door: KOOP"
    - title: Regelingenpocket Deventer
      text: Automatisch gegenereerde pocket van wet- en regelgeving van de organisatie Deventer
      metadata:
        - value: "Datum: 9-11-2018"
        - value: "Onderwerp: Overig"
        - value: "Gepubliceerd door: KOOP"
    - title: HAFIR Bestuurlijke regels
      text: Dit overzicht bevat bestuurlijke regels zoals de begrotingsregels of Raamwerk uitvoering subsidies die voor het Rijk van toepassing zijn.
      metadata:
        - value: "Datum: 6-2-2018"
        - value: "Onderwerp: Overig"
        - value: "Gepubliceerd door: Ministerie van FinanciÃ«n"
    - title: Wettenpocket Warenwet
      text: Automatisch gegenereerde pocket van wet- en regelgeving rond Warenwet
      metadata:
        - value: "Datum: 21-11-2018"
        - value: "Onderwerp: Overig"
        - value: "Gepubliceerd door: KOOP"
  paginationContext:
    previousPage: 1
    currentPage: 2
    lastPage: 5
