name: facet
context:
  items:
    - id: facet-01
      value: beschikbaar
      count: 12221
      group: status
    - id: facet-02
      value: In onderzoek
      count: 121
      group: status
      checked: true
    - id: facet-03
      value: Niet beschikbaar
      count: 50
      group: status
    - id: facet-04
      value: Gepland
      count: 25
      group: status