---
label: CVDR - Contentpage
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
    language: true
    skipLinks:
      - url: '#content'
        text: Direct naar content
  navWetContext:
    id: 2
    items:
    - title: Wettechnische gegevens
      href: "/components/preview/templates-cvdr-wettechnischegegevens"
      sub: false
  navToeContext:
    id: 3
    items:
    - title: Regeling
      sub: true
      active: true
      sactive: true
      subItems:
      - stitle: Intitul√©
        href: "#section-1"
      - stitle: Besluiten
        href: "#section-2"
      - stitle: Artikel 1
        href: "#artikel-1"
      - stitle: Artikel 2
        href: "#artikel-2"
  alertFoutief:
    heading: Ziet u een fout in deze regeling?
    text: Meld het ons op <a href="mailto:regelgeving@overheid.nl">regelgeving@overheid.nl</a>
    modifier: alert--success alert--lg icon--document
  pageactions:
    items:
    - link: '#'
      text: Permalink
      icon: icon-permalink.svg
      modal: true
    - link: '#'
      text: Fout in deze regeling
      icon: icon-alert-blue.svg
    - link: '#'
      text: Downloaden
      icon: icon-download.svg
    - link: '#'
      text: Printen
      icon: icon-print.svg
  tablecontainer1:
    topbar:
      items:
      - text: Toon volledige tabel
        href: '#'
        class: icon icon--fullscreen
