---
label: CVDR - Searchresults
status: prototype
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
  vanDatepicker:
    id: 786
    haslabel: true
    label: Van
  totDatepicker:
    id: 7836
    haslabel: true
    label: Tot
  postcodeInput:
    fieldLabelVisible: true
    fieldPlaceholder: Bijv. 1234 AB
    fieldLabel: Postcode
  wordintitelInput:
    id: 543
    fieldLabelVisible: true
    fieldPlaceholder: Zoekwoord
    fieldLabel: Zoekwoord in titel
  wordintextInput:
    id: 432
    fieldLabelVisible: true
    fieldPlaceholder: Zoekwoord
    fieldLabel: Woord in tekst
  wetgegevensInput:
    id: 321
    fieldLabelVisible: true
    fieldPlaceholder: Zoekwoord
    fieldLabel: Wetstechnische gegevens
  subselectionGemContext:
    linkText: Selecteer gemeenten
    id: 20
    modalTitle: Selecteer Gemeenten
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    searchFilter: true
    type: span
    Options:
      - Option: 1
        id: 1237
        title: Spanje
        short: Spanje
      - Option: 2
        id: 2237
        title: Griekenland
        short: Griekenland
      - Option: 3
        id: 3237
        title: Nederland
        short: Nederland
  subselectionProContext:
    linkText: Selecteer provincies
    id: 21
    modalTitle: Selecteer provincies
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    searchFilter: true
    type: span
    Options:
      - Option: 1
        id: 1346
        title: Zuid-Holland
        short: Zuid-Holland
      - Option: 2
        id: 2346
        title: Noord-Holland
        short: Noord-Holland
        checked: checked
      - Option: 3
        id: 3346
        title: Zeeland
        short: Zeeland
        checked: checked
  subselectionWatContext:
    linkText: Selecteer waterschappen
    id: 1900
    modalTitle: Selecteer waterschappen
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    searchFilter: true
    type: span
    Options:
      - Option: 4
        id: 4455
        title: Spanje
        short: Spanje
      - Option: 5
        id: 5455
        title: Griekenland
        short: Griekenland
      - Option: 6
        id: 6455
        title: Nederland
        short: Nederland
  subselectionRegContext:
    linkText: Selecteer regionale samenwerkingsorganen
    id: 119
    modalTitle: Selecteer regionale samenwerkingsorganen
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    searchFilter: true
    type: span
    Options:
      - Option: 42
        id: 4564
        title: Spanje
        short: Spanje
      - Option: 52
        id: 5564
        title: Griekenland
        short: Griekenland
      - Option: 62
        id: 6564
        title: Nederland
        short: Nederland
  subselectionDeeContext:
    linkText: Selecteer deelgemeenten / stadsdelen
    id: 122
    modalTitle: Selecteer deelgemeenten / stadsdelen
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    searchFilter: true
    type: span
    Options:
      - Option: 41
        id: 4563
        title: Spanje
        short: Spanje
      - Option: 51
        id: 5563
        title: Griekenland
        short: Griekenland
      - Option: 61
        id: 6563
        title: Nederland
        short: Nederland
  subselectionBesContext:
    linkText: Selecteer BES eilanden
    id: 125
    modalTitle: Selecteer BES eilanden
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    searchFilter: true
    type: span
    Options:
      - Option: 44
        id: 4562
        title: Spanje
        short: Spanje
      - Option: 55
        id: 5562
        title: Griekenland
        short: Griekenland
      - Option: 66
        id: 6562
        title: Nederland
        short: Nederland
  subselectionOndContext:
    linkText: Selecteer onderwerpen
    id: 1288
    modalTitle: Selecteer onderwerpen
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    searchFilter: true
    type: span
    Options:
      - Option: 444
        id: 4561
        title: Spanje
        short: Spanje
      - Option: 555
        id: 5561
        title: Griekenland
        short: Griekenland
      - Option: 666
        id: 6561
        title: Nederland
        short: Nederland
  onderwerpContext:
    moreless: true
    searchFilter: true
    options:
    - id: checkbox-20
      text: Alle
      name: onderwerp
    - id: checkbox-20
      text: Vandaag
      name: onderwerp
    - id: checkbox-20
      text: Afgelopen week
      name: onderwerp
    - id: checkbox-20
      text: Afgelopen maand
      name: onderwerp
    - id: checkbox-20
      text: Afgelopen 3 maanden
      name: onderwerp
    - id: checkbox-20
      text: Zelf een periode kiezen
      name: onderwerp
  sortContext:
    modifier:
    options:
    - label: Datum
      value: value
      active: is-active
    - label: Titel
      value: value
    amountPerPageFilter: true
  inputsubmitContext:
    label: Verfijn uw zoekopdracht
    showLabel: false
    placeholder: Verfijn uw zoekopdracht
    button: Zoek
    modifierComponent: input-inputsubmit--s
  resultsContext:
    modifier: result--list--wide
    items:
    - title: Voortgangsrapportage CTIVD over de werking Wiv2017
      titleHeader: h2
      label: Nieuw vandaag
      share: false
      buttons:
        - button: Bekijk publicatie
          type: secendary
      definitionlist: true
      definitionlistModifier: condensed
      definitionlistItems:
          - title: Geldendheidsperiode
            description: 01-01-2019 t/m heden
          - title: Uitgegeven door
            description: Samenwerkingsverband vastgoedinformatie
    - title: AppelAfdeling 1.2.1. Algemene bepaling voor het sluiten van schriftelijke overeenkomsten onder bezwarende titel voor het verrichten van werken, leveringen of dienstent
      titleHeader: h2
      label: Regeling vervallen per 01-01-2019
      labelType: danger
      buttons:
        - button: Bekijken
          type: secendary
      definitionlist: true
      definitionlistModifier: condensed
      definitionlistItems:
          - title: Geldendheidsperiode
            description: 01-01-2019 t/m heden
          - title: Uitgegeven door
            description: Samenwerkingsverband vastgoedinformatie
    - title: Voortgangsrapportage CTIVD over de werking Wiv2017
      titleHeader: h2
      share: false
      buttons:
        - button: Bekijk publicatie
          type: secendary
      definitionlist: true
      definitionlistModifier: condensed
      definitionlistItems:
          - title: Geldendheidsperiode
            description: 01-01-2019 t/m heden
          - title: Uitgegeven door
            description: Samenwerkingsverband vastgoedinformatie
    - title: Voortgangsrapportage CTIVD over de werking Wiv2017
      titleHeader: h2
      share: false
      buttons:
        - button: Bekijk publicatie
          type: secendary
      definitionlist: true
      definitionlistModifier: condensed
      definitionlistItems:
          - title: Geldendheidsperiode
            description: 01-01-2019 t/m heden
          - title: Uitgegeven door
            description: Samenwerkingsverband vastgoedinformatie
    - title: Voortgangsrapportage CTIVD over de werking Wiv2017
      titleHeader: h2
      share: false
      buttons:
        - button: Bekijk publicatie
          type: secendary
      definitionlist: true
      definitionlistModifier: condensed
      definitionlistItems:
          - title: Geldendheidsperiode
            description: 01-01-2019 t/m heden
          - title: Uitgegeven door
            description: Samenwerkingsverband vastgoedinformatie
  inputSearchContext:
    modifier: input-text--searchmedium
    id: 1
    fieldLabel: Postcode
    fieldLabelVisible: false
    fieldInstruction:
    fieldPlaceholder: Verfijn op zoekwoord
    remove: true

  inputsubmitSearchSaveContext:
    label: Uw e-mailadres
    showLabel: true
    placeholder: Uw e-mailadres
    button: Bevestigen
  buttonswitchContext:
    text: banner
    buttons:
      - label: Kaart
        active: true
        icon: marker
      - label: Lijst
        active: false
        icon: hamburger
  selectedfilterContext:
    items:
      - label: Gezocht op "leveringen"
        url: "#"
      - label: Bouwvergunning
        url: "#"
      - label: APV vergunning
        url: "#"
  subselectionContext:
    linkText: Selecteer organisatie(s)
    id: 1
    modalTitle: Selecteer organisatie(s)
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    searchFilter: true
    type: span
    Options:
      - Option: 1
        id: 1
        title: Spanje
        short: Spanje
      - Option: 2
        id: 2
        title: Griekenland
        short: Griekenland
      - Option: 3
        id: 3
        title: Nederland
        short: Nederland
  subselectionThemaContext:
    linkText: Selecteer thema(s)
    id: 12
    modalTitle: Selecteer thema(s)
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    searchFilter: true
    type: span
    Options:
      - Option: 4
        id: 4
        title: Spanje
        short: Spanje
      - Option: 5
        id: 5
        title: Griekenland
        short: Griekenland
      - Option: 6
        id: 6
        title: Nederland
        short: Nederland
  subselectionInfoContext:
    linkText: Selecteer informatiesoort(en)
    id: 12
    modalTitle: Selecteer informatiesoort(en)
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    searchFilter: true
    type: span
    Options:
      - Option: 4
        id: 4
        title: Spanje
        short: Spanje
      - Option: 5
        id: 5
        title: Griekenland
        short: Griekenland
      - Option: 6
        id: 6
        title: Nederland
        short: Nederland





