title: Button icon
status: prototype
context:
  text: Knop icoon
variants:
  - name: default
    status: prototype
  - name: Plus
    status: prototype
    notes: This variant is used for small icons in toolbars etc. It has a smaller padding than the default icon button and no background color.
    context:
      modifier: button-icon--plus
      text: Toevoegen
  - name: Min
    status: prototype
    notes: This variant is used for small icons in toolbars etc. It has a smaller padding than the default icon button and no background color.
    context:
      modifier: button-icon--min
      text: Verwijderen
