---
label: Subselection
context:
  name: Default
  id: 1777778
  type: abbr
  linkText: Selecteer
  modalTitle: Selecteer ministeries
  fieldLabel: fieldLabel
  fieldInstruction:
  fieldPlaceholder: 'Bijv: 0612345678'
  Options:
    - Option: 1777778
      id: 1777778
      title: Landbouw, Natuur en Voedselkwaliteit (lnv)
      short: lnv
      checked: checked
    - Option: 2777778
      id: 2777778
      title: Onderwijs, Cultuur en Wetenschap (ocw)
      short: ocw
    - Option: 3777778
      id: 3777778
      title: Sociale Zaken en Werkgelegenheid (szw)
      short: szw
variants:
  - name: Secondary
    context:
      id: 98761
      modifier: secondary
      type: span
      Options:
        - Option: 1999987
          id: 1999987
          title: Landbouw, Natuur en Voedselkwaliteit (lnv)
          short: lnv
          checked: checked
        - Option: 2999988
          id: 2999988
          title: Onderwijs, Cultuur en Wetenschap (ocw)
          short: ocw
        - Option: 3999989
          id: 3999989
          title: Sociale Zaken en Werkgelegenheid (szw)
          short: szw
  - name: Default (span)
    context:
      id: 98762
      type: span
      linkText: Kies 'iets'
      linkTextActive: Wijzig selectie
      modalTitle: Selecteer ministeries
      fieldLabel: fieldLabel
      fieldInstruction:
      fieldPlaceholder: 'Bijv: 0612345678'
      Options:
        - Option: 199998
          id: 199998
          title: Landbouw, Natuur en Voedselkwaliteit (lnv)
          short: lnv
          checked: checked
        - Option: 299998
          id: 299998
          title: Onderwijs, Cultuur en Wetenschap (ocw)
          short: ocw
        - Option: 399998
          id: 399998
          title: Sociale Zaken en Werkgelegenheid (szw)
          short: szw
  - name: With Search filter
    label: met Zoekfilter
    context:
      id: 98763
      searchFilter: true
      label: Zoek thema
      Options:
        - Option: 1999981
          id: 1999981
          title: Landbouw, Natuur en Voedselkwaliteit (lnv)
          short: lnv
          checked: checked
        - Option: 2999982
          id: 2999982
          title: Onderwijs, Cultuur en Wetenschap (ocw)
          short: ocw
        - Option: 3999983
          id: 3999983
          title: Sociale Zaken en Werkgelegenheid (szw)
          short: szw
  - name: With Limit (3)
    label: met Limiet (3)
    context:
      id: 98764
      type: div
      linkText: Kies 'iets'
      linkTextActive: Wijzig selectie
      modalTitle: Selecteer ministeries
      fieldLabel: fieldLabel
      fieldInstruction:
      fieldPlaceholder: 'Bijv: 0612345678'
      maxShow: 3
      Options:
        - Option: 1
          id: 6541
          title: Nederland
          short: Nederland
          checked: checked
        - Option: 2
          id: 6542
          title: Frankrijk
          short: Frankrijk
          checked: checked
        - Option: 3
          id: 6543
          title: Griekenland
          short: Griekenland
          checked: checked
        - Option: 4
          id: 6544
          title: Spanje
          short: Spanje
          checked: checked
        - Option: 5
          id: 6545
          title: Zweden
          short: Zweden
        - Option: 6
          id: 6546
          title: Nederland
          short: Nederland
        - Option: 7
          id: 6547
          title: Frankrijk
          short: Frankrijk
        - Option: 8
          id: 6548
          title: Griekenland
          short: Griekenland
        - Option: 9
          id: 6549
          title: Spanje
          short: Spanje
        - Option: 10
          id: 65410
          title: Zweden
          short: Zweden
        - Option: 11
          id: 65411
          title: Nederland
          short: Nederland
        - Option: 12
          id: 65412
          title: Frankrijk
          short: Frankrijk
        - Option: 13
          id: 65413
          title: Griekenland
          short: Griekenland
        - Option: 14
          id: 65414
          title: Spanje
          short: Spanje
        - Option: 15
          id: 65415
          title: Zweden
          short: Zweden
        - Option: 16
          id: 65416
          title: Nederland
          short: Nederland
        - Option: 17
          id: 65417
          title: Frankrijk
          short: Frankrijk
        - Option: 18
          id: 65418
          title: Griekenland
          short: Griekenland
        - Option: 19
          id: 65419
          title: Spanje
          short: Spanje
        - Option: 20
          id: 65420
          title: Zweden
          short: Zweden
        - Option: 21
          id: 65421
          title: Nederland
          short: Nederland
        - Option: 22
          id: 65422
          title: Frankrijk
          short: Frankrijk
        - Option: 23
          id: 65423
          title: Griekenland
          short: Griekenland
        - Option: 24
          id: 65424
          title: Spanje
          short: Spanje
        - Option: 25
          id: 65425
          title: Zweden
          short: Zweden
        - Option: 26
          id: 65426
          title: Nederland
          short: Nederland
        - Option: 27
          id: 65427
          title: Frankrijk
          short: Frankrijk
        - Option: 28
          id: 65428
          title: Griekenland
          short: Griekenland
        - Option: 29
          id: 65429
          title: Spanje
          short: Spanje
        - Option: 30
          id: 65430
          title: Zweden
          short: Zweden
        - Option: 31
          id: 65431
          title: Nederland
          short: Nederland
        - Option: 32
          id: 65432
          title: Frankrijk
          short: Frankrijk
        - Option: 33
          id: 65433
          title: Griekenland
          short: Griekenland
        - Option: 34
          id: 65434
          title: Spanje
          short: Spanje
        - Option: 35
          id: 65435
          title: Zweden
          short: Zweden
        - Option: 36
          id: 65436
          title: Nederland
          short: Nederland
        - Option: 37
          id: 65437
          title: Frankrijk
          short: Frankrijk
        - Option: 38
          id: 65438
          title: Griekenland
          short: Griekenland
        - Option: 39
          id: 65439
          title: Spanje
          short: Spanje
        - Option: 40
          id: 65440
          title: Zweden
          short: Zweden
        - Option: 41
          id: 65441
          title: Nederland
          short: Nederland
        - Option: 42
          id: 65442
          title: Frankrijk
          short: Frankrijk
        - Option: 43
          id: 65443
          title: Griekenland
          short: Griekenland
        - Option: 44
          id: 65444
          title: Spanje
          short: Spanje
        - Option: 45
          id: 65445
          title: Zweden
          short: Zweden
        - Option: 46
          id: 65446
          title: Nederland
          short: Nederland
        - Option: 47
          id: 65447
          title: Frankrijk
          short: Frankrijk
        - Option: 48
          id: 65448
          title: Griekenland
          short: Griekenland
        - Option: 49
          id: 65449
          title: Spanje
          short: Spanje
        - Option: 50
          id: 65450
          title: Zweden
          short: Zweden
  - name: with Check all
    label: met Selecteer alle
    context:
      id: 65498765
      type: span
      selectAll: true
      selectAllID: 123211
  - name: with Check all options
    label: met Selecteer alle opties
    context:
      id: 65498766
      type: span
      selectAll: true
      selectAllID: 9877
      selectAllOnMain:
        label: Selecteer alle opties
      Options:
        - Option: 19999811
          id: 19999811
          title: Landbouw, Natuur en Voedselkwaliteit (lnv)
          short: lnv
          checked: checked
        - Option: 29999822
          id: 29999822
          title: Onderwijs, Cultuur en Wetenschap (ocw)
          short: ocw
        - Option: 39999833
          id: 39999833
          title: Sociale Zaken en Werkgelegenheid (szw)
          short: szw
  - name: With Check All - multiple
    label: met Selecteer alle (meerdere)
    context:
      id: 98766
      type: span
      linkText: Kies 'iets anders'
      linkTextActive: Wijzig selectie
      modalTitle: Selecteer uit deze themas
      fieldLabel: fieldLabel
      fieldInstruction:
      fieldPlaceholder: 'Bijv: 0612345678'
      maxShow: 3
      multilevel: true
      Options:
        - Option: 1
          id: 1
          title: Nederland
          short: Nederland
          checkAll: true
          OptionsSubs:
            - OptionsSub: 11776
              id: 11776
              title: NederlandSub1
              short: NederlandSub1
              checked: checked
            - OptionsSub: 12776
              id: 12776
              title: NederlandSub2
              short: NederlandSub2
        - Option: 2776
          id: 2776
          title: Frankrijk
          short: Frankrijk
          checkAll: true
          OptionsSubs:
            - OptionSub: 21776
              id: 21776
              title: FrankrijkSub1
              short: FrankrijkSub1
            - OptionSub: 22776
              id: 22776
              title: FrankrijkSub2
              short: FrankrijkSub2
  - name: With Catagories
    label: met Categorieen
    context:
      id: 98767
      linkText: Kies 'Publicerende organisatie(s)'
      linkTextActive: Wijzig selectie
      modalTitle: Publicerende organisatie(s)
      label: Filter op zoekwoord of zinsdeel
      inputPlaceholder: 'Zoekwoord of zinsdeel'
      maxShow: 3
      type: span
      searchFilter: true
      multilevel: true
      Options:
        - Option: 15567
          id: 15567
          title: Adviescollege
          short: Adviescollege
          OptionsSubs:
            - OptionsSub: 115567
              id: 115567
              title: Algemene Rekenkamer
              short: Algemene Rekenkamer
            - OptionsSub: 125567
              id: 125567
              title: Raad voor Cultuur
              short: Raad voor Cultuur
            - OptionsSub: 135567
              id: 135567
              title: Raad voor Strafrechtstoepassing en Jeugdbescherming (RSJ)
              short: Raad voor Strafrechtstoepassing en Jeugdbescherming (RSJ)
            - OptionsSub: 145567
              id: 145567
              title: Raad voor Werk en Inkomen
              short: Raad voor Werk en Inkomen
        - Option: 25567
          id: 25567
          title: Deelgemeente
          short: Deelgemeente
          OptionsSubs:
            - OptionSub: 215567
              id: 215567
              title: Amsterdam - Bos en Lommer
              short: Amsterdam - Bos en Lommer
            - OptionSub: 225567
              id: 225567
              title: Amsterdam - Geuzenveld-Slotermeer
              short: Amsterdam - Geuzenveld-Slotermeer
            - OptionSub: 235567
              id: 235567
              title: Amsterdam - Nieuw-West
              short: Amsterdam - Nieuw-West
            - OptionSub: 245567
              id: 245567
              title: Amsterdam - Noord
              short: Amsterdam - Noord
            - OptionSub: 255567
              id: 2255567
              title: Amsterdam - Oost
              short: Amsterdam - Oost
        - Option: 35567
          id: 35567
          title: Hoge college van staat
          short: Hoge college van staat
          OptionsSubs:
            - OptionSub: 2115567
              id: 2115567
              title: Algemene rekenkamer
              short: Algemene rekenkamer
            - OptionSub: 2215567
              id: 2215567
              title: Hoge raad van Adel
              short: Hoge raad van Adel
            - OptionSub: 2315567
              id: 2315567
              title: Kabinet der Koningin
              short: Kabinet der Koningin
            - OptionSub: 2415567
              id: 2415567
              title: Kanselarij der Nederlandse Orden
              short: Kanselarij der Nederlandse Orden
            - OptionSub: 2515567
              id: 22515567
              title: Nationale Ombudsman
              short: Nationale Ombudsman
  - name: With Catagories and select all
    label: met Button Check all en Categorieen
    context:
      id: 98768
      linkText: Kies 'Publicerende organisatie(s)'
      linkTextActive: Wijzig selectie
      modalTitle: Publicerende organisatie(s)
      label: Zoek publicerende organisatie(s)
      inputPlaceholder: 'Zoekwoord'
      maxShow: 3
      type: span
      searchFilter: true
      multilevel: true
      buttonResetForm: true
      controls:
        selectAllLabel: Selecteer alle organisaties
      Options:
        - Option: 144456
          id: 144456
          title: Adviescollege
          short: Adviescollege
          OptionsSubs:
            - OptionsSub: 1144456
              id: 1144456
              title: Algemene Rekenkamer
              short: Algemene Rekenkamer
            - OptionsSub: 1244456
              id: 1244456
              title: Raad voor Cultuur
              short: Raad voor Cultuur
            - OptionsSub: 1344456
              id: 1344456
              title: Raad voor Strafrechtstoepassing en Jeugdbescherming (RSJ)
              short: Raad voor Strafrechtstoepassing en Jeugdbescherming (RSJ)
            - OptionsSub: 1444456
              id: 1444456
              title: Raad voor Werk en Inkomen
              short: Raad voor Werk en Inkomen
        - Option: 244456
          id: 244456
          title: Deelgemeente
          short: Deelgemeente
          OptionsSubs:
            - OptionSub: 2144456
              id: 2144456
              title: Amsterdam - Bos en Lommer
              short: Amsterdam - Bos en Lommer
            - OptionSub: 2244456
              id: 2244456
              title: Amsterdam - Geuzenveld-Slotermeer
              short: Amsterdam - Geuzenveld-Slotermeer
            - OptionSub: 2344456
              id: 2344456
              title: Amsterdam - Nieuw-West
              short: Amsterdam - Nieuw-West
            - OptionSub: 2444456
              id: 2444456
              title: Amsterdam - Noord
              short: Amsterdam - Noord
            - OptionSub: 2544456
              id: 22544456
              title: Amsterdam - Oost
              short: Amsterdam - Oost
        - Option: 3
          id: 3
          title: Hoge college van staat
          short: Hoge college van staat
          OptionsSubs:
            - OptionSub: 21144456
              id: 21144456
              title: Algemene rekenkamer
              short: Algemene rekenkamer
            - OptionSub: 22144456
              id: 22144456
              title: Hoge raad van Adel
              short: Hoge raad van Adel
            - OptionSub: 23144456
              id: 23144456
              title: Kabinet der Koningin
              short: Kabinet der Koningin
            - OptionSub: 24144456
              id: 24144456
              title: Kanselarij der Nederlandse Orden
              short: Kanselarij der Nederlandse Orden
            - OptionSub: 25144456
              id: 225144456
              title: Nationale Ombudsman
              short: Nationale Ombudsman
