---
label: Wachtwoord wijzigen
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
    navLinks:
      - url: '#'
        text: Home
      - url: '#'
        text: Uitgebreid zoeken
      - url: '#'
        text: 'Mijn abonnementen'
        className: is-active
      - url: '#'
        text: Help
        modifier: secondary
    youAreHere:
      - text: Publicaties > OfficiÃ«le publicaties
    skipLinks:
      skipLinks:
        - url: '#content'
          text: Direct naar content
    metaLinks:
      - profile: true
        profileContext:
          id: 12
          loggedIn: true
          textLoggedIn: Profiel
          options:
            - text: Mijn abonnementen
              url: '#'
              class: link link--forgotpw
            - text: Wachtwoord wijzigen
              url: '#'
              class: link link--edit
            - text: E-mailadres wijzigen
              url: '#'
              class: link link--edit
            - text: Account verwijderen
              url: '#'
              class: link link--remove
            - text: Uitloggen
              url: '#'
              class: link link--logout
  breadcrumb:
    breadcrumb:
    - text: Home
      url: '#'
    - text: Berichtgeving
      url: '#'
    - text: X
  emailInput:
    modifier:
    id: 1
    fieldLabel: E-mailadres
    fieldLabelVisible: true
    labelmodifier: accent
    fieldInstruction:
    fieldPlaceholder: Bijv. uwnaam@koop.overheid.nl
    disabled: true
    value: uwnaam@koop.overheid.nl
  oldPWInput:
    modifier:
    id: 222
    type: password
    fieldLabel: Huidig wachtwoord
    fieldLabelVisible: true
    labelmodifier: accent
    fieldInstruction:
    fieldPlaceholder: Huidig wachtwoord
    required: true
    requiredLabel: true
  newPWInput:
    modifier:
    id: 2
    type: password
    class: js-passwordstrength__input
    fieldLabel: Nieuw wachtwoord
    fieldLabelVisible: true
    labelmodifier: accent
    fieldInstruction:
    fieldPlaceholder: Nieuw wachtwoord
    required: true
    requiredLabel: true
  repeatPWInput:
    modifier:
    id: 3
    type: password
    class: js-passwordstrength__inputrepeat
    fieldLabel: Herhaal wachtwoord
    fieldLabelVisible: true
    labelmodifier: accent
    fieldInstruction:
    fieldPlaceholder: Herhaal nieuw wachtwoord
    required: true
    requiredLabel: true
  buttonSubmit:
      id: 123
      text: Bevestigen
      button: true
      type: submit
      modifier: button--primary form__button
  linkBack:
    text: Terug naar Mijn abonnementen
  preheader:
    value: Mijn abonnementen
