---
label: Account activeren
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
    navLinks:
      - url: '#'
        text: Home
      - url: '#'
        text: Uitgebreid zoeken
      - url: '#'
        text: 'Mijn abonnementen'
        className: is-active
      - url: '#'
        text: Help
        modifier: secondary
    youAreHere:
      - text: Publicaties > Officiële publicaties
    skipLinks:
      skipLinks:
        - url: '#content'
          text: Direct naar content
    metaLinks:
      - profile: true
        profileContext:
          id: 12
          loggedIn: false
          buttonLogin:
            text: Inloggen
            anchor: true
            action: '#'
  breadcrumb:
    title: "U bent hier:"
    breadcrumb:
    - text: Home
      url: '#'
    - text: Mijn Abonnementen
      url: '#'
    - text: Activeer uw account

  inputEmailContext:
    id: 1
    required: true
    patterntype: email
    fieldLabel: E-mailadres
    fieldLabelVisible: true
    fieldInstruction:
    fieldPlaceholder: Uw e-mailadres
  inputCodeContext:
    id: 2
    required: true
    type: text
    fieldLabel: Activeringscode
    fieldLabelVisible: true
    fieldInstruction:
    fieldPlaceholder:
    hastooltip: true
    tooltipContext:
      id: 1231
      content: De activeringscode uit de activeringse-mail
  linkNewcode:
    text: Nieuwe activeringscode aanvragen
  linkAccount:
    text: Ik heb al een account
  buttonSubmit:
    id: 123
    text: Activeer account
    button: true
    type: submit
    modifier: button--primary form__button
  alert:
    text: Wij hebben u een activeringse-mail gestuurd, indien uw e-mailadres nog niet bij ons is geregistreerd.
  preheader:
    value: Officiële bekendmakingen
