---
label: Input text
status: ready
context:
  id: 1
  fieldLabel: Voornaam
  fieldInstruction:
  fieldPlaceholder: 'Bijv: Jan de Vries'
variants:
  - name: postal code
    label: input postcode
    context:
      modifier: input--postalcode
      id: 1
      fieldLabel: Postcode
      fieldInstruction:
      fieldPlaceholder: 'Bijv: 2282LL'
