---
label: Definitionlist
context:
  items:
    - type: Status
      value: Compleet
variants:
  - name: data
    context:
      modifier: "columns--data"
      divContainer: true
      items:
        - type: Thema
          value: Huisvesting
          modifier: icon--housing
        - type: Status
          value: Beschikbaar
        - type: Toegang
          value: Publiek
        - type: Update
          value: 8-1-2018
        - type: Licentie
          value: CC-0
        - type: Taal
          value: Nederlands
