---
label: Verdr. - Homepage uitgebreid
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
    language: true
  jumbotronContext:
    heading: Verdragen van het Koninkrijk der Nederlanden
    hstyle: h2
    subheading: Verdragenbank
    intro: In de Verdragenbank zoekt u naar gegevens van verdragen waarbij het Koninkrijk der Nederlanden deelgenoot is.
    centered: true
    size: medium
    inputZoekwoord:
      modifier: input-text--searchmedium
      fieldPlaceholder: Zoekwoord of verdragsnummer
      fieldLabel: Zoek in de Verdragenbank
      fieldLabelVisible: true
      labelmodifier: medium
    dateselection:
      dateselectionDatum:
        label: Totstandgekomen op
    typeverdagContext:
      moreless: true
      options:
      - id: checkbox-220
        text: Bilateraal
        name: onderwerp
      - id: checkbox-221
        text: Multilateraal
        name: onderwerp
      - id: checkbox-222
        text: Plurilateraal
        name: onderwerp
    geldvoorContext:
      options:
      - id: checkbox-40
        text: Nederland (in Europa)
        name: onderwerp
      - id: checkbox-41
        text: Nederland (Bonaire)
        name: onderwerp
      - id: checkbox-422
        text: Nederland (Sint Eustatius)
        name: onderwerp
      - id: checkbox-4223
        text: Aruba
        name: onderwerp
      - id: checkbox-4224
        text: Curacao
        name: onderwerp
      - id: checkbox-4225
        text: Sint Maarten
        name: onderwerp
    depositarisContext:
      moreless: true
      options:
      - id: checkbox-30
        text: Enkel deze verdragen tonen
        name: onderwerp
    geldendContext:
      moreless: true
      options:
      - id: checkbox-40
        text: Enkel deze verdragen tonen
        name: onderwerp
    subselectionContext:
      linkText: Selecteer partij(en)
      id: 1
      modalTitle: Selecteer partijen
      fieldLabel: fieldLabel
      fieldInstruction:
      fieldPlaceholder: 'Bijv: 0612345678'
      searchFilter: true
      type: span
      Options:
        - Option: 122
          id: 122
          title: Spanje
          short: Spanje
        - Option: 222
          id: 222
          title: Griekenland
          short: Griekenland
        - Option: 322
          id: 322
          title: Nederland
          short: Nederland
    subselectionOnderwerpContext:
      linkText: Selecteer onderwerp(en)
      id: 23
      modalTitle: Selecteer onderwerp(en)
      fieldLabel: fieldLabel
      fieldInstruction:
      fieldPlaceholder: 'Bijv: 0612345678'
      type: span
      Options:
        - Option: 1
          id: 1
          title: Spanje
          short: Spanje
        - Option: 2
          id: 2
          title: Griekenland
          short: Griekenland
        - Option: 3
          id: 3
          title: Nederland
          short: Nederland
    tt1Context:
      id: 112
    tt2Context:
      id: 113
    tt3Context:
      id: 114
    tt4Context:
      id: 115
    tt5Context:
      id: 116
    tt6Context:
      id: 117
    tt7Context:
      id: 118
    startDatepicker:
      id: 234
      haslabel: true
      labelmodifier: secondary
      label: Vanaf
      fieldPlaceholder: DD-MM-JJJJ
    endDatepicker:
      id: 345
      haslabel: true
      labelmodifier: secondary
      label: Tot en met
      fieldPlaceholder: DD-MM-JJJJ
    inputPlaats:
      id: 98765
      fieldPlaceholder: Plaats totstandkoming
      fieldLabelVisible: true
      fieldLabel: Plaats
      labelmodifier: accent
    inputJaargang:
      id: 987656
      type: number
      fieldPlaceholder: JJJJ
      fieldLabelVisible: true
      fieldLabel: Jaargang
      labelmodifier: accent
    inputNummer:
      id: 987657
      type: number
      fieldPlaceholder: '000'
      fieldLabelVisible: true
      fieldLabel: Nummer
      labelmodifier: accent
  newsletterCheckbox:
    options:
    - id: checkbox-112312312
      text: Ik begrijp dat ...
      name: agreement
  newslCollap:
    heading: Lees meer over uw privacy
    id: 11231231
    text: Meer informatie over privacy en andere zaken
