label: Inline icon
context:
    text: icon text
    modifier: icon--overheid
    href: '#'
variants:
  - name: download icon
    label: download icon
    context:
      text: Download icon
      modifier: icon--download
  - name: remove icon
    label: remove icon
    context:
      text: Verwijderen icon
      modifier: icon--remove

