title: Tabs
context:
  tabs:
    - id: 1
      label: Particulieren
      content: <h2>Particulieren</h2><p>Informatie voor particulieren bevat een aantal links naar websites waar speciaal voor particulieren informatie te vinden is.</p>
    - id: 2
      label: Ondernemers
      content: <h2>Ondernemers</h2><p><p>Informatie speciaal voor ondernemers is te vinden op de website Ondernemersplein.nl.</p>
    - id: 3
      label: Berichten over uw buurt
      content: <h2>Berichten over uw buurt</h2><p>Zoek in berichten en bekendmakingen van voornamelijk gemeenten, provincies en waterschappen.</p>
variants:
  - name: Justified
    context:
      modifier: tabs--justified
      tabs:
        - id: 1
          label: Particulieren
          content: <h2>Particulieren</h2><p>Informatie voor particulieren bevat een aantal links naar websites waar speciaal voor particulieren informatie te vinden is.</p>
        - id: 2
          label: Ondernemers
          content: <h2>Ondernemers</h2><p><p>Informatie speciaal voor ondernemers is te vinden op de website Ondernemersplein.nl.</p>
        - id: 3
          label: Berichten over uw buurt
          content: <h2>Berichten over uw buurt</h2><p>Zoek in berichten en bekendmakingen van voornamelijk gemeenten, provincies en waterschappen.</p>
