---
title: Landingpage
label: ONL - Landingpagina
status: ready
context:
  headerContext:
    metaLinks:
      - url: '#'
        text: MijnOverheid.nl
  rowLanding:
    - image: '../../images/temp/homepage-beleid.jpg'
      title: Beleid & Regelgeving
      intro: Hier bekijkt u publicaties omtrent beleid, wet- en regelgeving.
  linkSetGroup:
    - linkSet:
      - title: Beleidsonderzoek
        links:
          - url: https://www.wrr.nl
            text: Wetenschappelijke Raad voor het Regeringsbeleid (WRR)
          - url: https://www.cpb.nl/
            text: Centraal Planbureau (CPB)
          - url: https://www.scp.nl/
            text: Sociaal en Cultureel Planbureau (SCP)
          - url: https://www.cbs.nl
            text: Centraal Bureau voor de Statistiek (CBS)
          - url: https://www.wodc.nl
            text: Wetenschappelijk Onderzoek- en Documentatiecentrum (WODC)
          - url: https://www.pbl.nl/
            text: Planbureau voor de Leefomgeving (PBL)
          - url: https://www.arbeidenoverheid.nl/
            text: Kennisbank Arbeidszaken Publieke Sector (KAPS)
      - title: Advies en besluitvorming
        links:
          - url: http://internetconsultatie.overheid.nl
            text: Internetconsultatie
          - url: http://www.raadvanstate.nl/adviezen.html
            text: Adviezen Raad van State
          - url: https://zoek.officielebekendmakingen.nl/zoeken/parlementaire_documenten
            text: Parlementaire documenten (bijvoorbeeld Kamervragen, Kamerstukken)
          - urL: http://almanak.overheid.nl/categorie/53/Adviescolleges/
            text: Meer adviesorganen
      - title: Bekendmaking
        links:
          - url: https://zoek.officielebekendmakingen.nl/zoeken/staatsblad
            text: Staatsblad (landelijk)
          - url: https://zoek.officielebekendmakingen.nl/zoeken/staatscourant
            text: Staatscourant (landelijk)
          - url: https://zoek.officielebekendmakingen.nl/zoeken/tractatenblad
            text: Tractatenblad (landelijk)
          - url: https://zoek.officielebekendmakingen.nl/zoeken/gemeenteblad
            text: Gemeenteblad
          - url: https://zoek.officielebekendmakingen.nl/zoeken/provinciaal_blad
            text: Provinciaal blad
          - url: https://zoek.officielebekendmakingen.nl/zoeken/waterschapsblad
            text: Waterschapsblad
          - url: https://zoek.officielebekendmakingen.nl/zoeken/blad_gemeenschappelijke_regeling
            text: Blad gemeenschappelijke regeling
          - url: https://www.officielebekendmakingen.nl
            text: OfficiÃ«le bekendmakingen vandaag
          - url: https://zoek.overheid.nl/berichten_over_uw_buurt_eenvoudig_zoeken
            text: Publicaties op websites van gemeenten, provincies, waterschappen en regionale samenwerkingsverbanden
      - title: Wet- en regelgeving
        links:
          - url: http://eur-lex.europa.eu/collection/eu-law.html
            text: Europees
          - url: http://wetten.overheid.nl
            text: Landelijk
          - url: https://wetgevingskalender.overheid.nl/
            text: Wetgevingskalender
          - url: http://zoekdienst.overheid.nl/ictu_website/CVDR/CVDRZoeken.aspx?searchtype=Simple&amp;connection=CVDR
            text: Plaatselijk (gemeente, provincie, waterschap, regionaal samenwerkingsverband)
          - url: http://www.ruimtelijkeplannen.nl
            text: Ruimtelijkeplannen.nl
    - linkSet:
      - title: Uitvoering
        links:
          - url: http://wetten.overheid.nl
            text: Landelijk (beleidsregels, circulaires, uitvoeringsaanwijzingen)
          - url: http://www.overheid.nl/overheidsinformatie/vergunningen
            text: Plaatselijke vergunningen
          - url: http://vergunningenbank.overheid.nl/natuurbeschermingswet
            text: Vergunningen Natuurbeschermingswet
      - title: Klachten en rechtspraak
        links:
          - url: http://mensenrechten.nl/publicaties/oordelen
            text: College voor de Rechten van de Mens
          - url: http://www.nationaleombudsman.nl/
            text: Nationale ombudsman
          - url: http://www.rechtspraak.nl
            text: Rechtspraak.nl
          - url: http://tuchtrecht.overheid.nl/nieuw
            text: Tuchtrecht
      - title: Toezicht
        links:
          - url: http://www.inspectieloket.nl
            text: Inspectieloket
