---
label: ONL 2.0 - Searchresults
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
  sortContext:
    modifier:
    columns: true
    amountPerPageFilter: true
    buttonDownload: false
    options:
    - label: Datum
      value: value
      active: is-active
    - label: Titel
      value: value
  resultsContext:
    modifier: result--list--wide
    items:
    - title: Aangepast eindexamen voortgezet onderwijs bij bijzondere omstandigheden
      titleHeader: h2
      label: Nieuw vandaag
      text: Doe je eindexamen in het voortgezet onderwijs? En heb je een handicap of beperking? Dan kan je school bij het examen daarmee rekening houden.
      share: false
      metadataDates:
        - value: Ministerie van Onderwijs, Cultuur en Wetenschap (Ministerie)
        - value: "2020-01-22T14:49:42.458Z"
      buttons:
        - button: Bekijken
          type: icon button--icon-external
    - title: Aangepast eindexamen voortgezet onderwijs bij bijzondere omstandigheden
      titleHeader: h2
      text: Doe je eindexamen in het voortgezet onderwijs? En heb je een handicap of beperking? Dan kan je school bij het examen daarmee rekening houden.
      share: false
      metadataDates:
        - value: Ministerie van Onderwijs, Cultuur en Wetenschap (Ministerie)
        - value: "2020-01-22T14:49:42.458Z"
      buttons:
        - button: Bekijken
          type: icon button--icon-external
    - title: Aangepast eindexamen voortgezet onderwijs bij bijzondere omstandigheden
      titleHeader: h2
      text: Doe je eindexamen in het voortgezet onderwijs? En heb je een handicap of beperking? Dan kan je school bij het examen daarmee rekening houden.
      share: false
      metadataDates:
        - value: Ministerie van Onderwijs, Cultuur en Wetenschap (Ministerie)
        - value: "2020-01-22T14:49:42.458Z"
      buttons:
        - button: Bekijken
          type: icon button--icon-external
    - title: Aangepast eindexamen voortgezet onderwijs bij bijzondere omstandigheden
      titleHeader: h2
      text: Doe je eindexamen in het voortgezet onderwijs? En heb je een handicap of beperking? Dan kan je school bij het examen daarmee rekening houden.
      share: false
      metadataDates:
        - value: Ministerie van Onderwijs, Cultuur en Wetenschap (Ministerie)
        - value: "2020-01-22T14:49:42.458Z"
      buttons:
        - button: Bekijken
          type: icon button--icon-external
  inputsubmitContext:
    id: 9657
    label: Verfijn uw zoekopdracht
    showLabel: false
    placeholder: Verfijn uw zoekopdracht
    button: Zoeken
    modifierComponent: input-inputsubmit--s
  digitaalaanvragenContext:
    options:
    - id: radio-1
      text: Ja (10)
      name: publicatie
    - id: radio-2
      text: Nee (10)
      name: publicatie
    - id: radio-3
      text: DigiD (10)
      name: publicatie
  postcodeContext:
    labelmodifier: accent
    id: 2
    fieldLabel: Postcode
    fieldLabelVisible: true
    fieldPlaceholder: Bijv. 1222AB
  checkallDienstenvoorContext:
    id: 1
    label: doelgroepen
    checkboxes:
      options:
      - id: checkbox-20
        text: Ondernemers
        name: onderwerp
      - id: checkbox-21
        text: Particulieren
        name: onderwerp
  gewijzigdContext:
    name: alliedforces
    options:
      - id: checkbox-1
        text: Afgelopen week
        name: segment
      - id: checkbox-2
        text: Huidige jaar
        name: segment
      - id: checkbox-3
        text: Eerder
        name: segment
  checkallDienstenvanContext:
    id: 2
    label: organisaties
    checkboxes:
      options:
      - id: checkbox-202
        text: Gemeente
        name: onderwerp2
      - id: checkbox-212
        text: Provincie
        name: onderwerp2
      - id: checkbox-222
        text: Regionaal Samenwerkingsorgaan
        name: onderwerp2
      - id: checkbox-232
        text: Rijkswaterstaat
        name: onderwerp2
      - id: checkbox-242
        text: Waterschap
        name: onderwerp2
