---
label: Subselection
context:
  name: Default
  id: 1
  type: abbr
  linkText: Selecteer
  modalTitle: Selecteer ministeries
  fieldLabel: fieldLabel
  fieldInstruction:
  fieldPlaceholder: 'Bijv: 0612345678'
  Options:
    - Option: 1
      id: 1
      title: Landbouw, Natuur en Voedselkwaliteit (lnv)
      short: lnv
      checked: checked
    - Option: 2
      id: 2
      title: Onderwijs, Cultuur en Wetenschap (ocw)
      short: ocw
    - Option: 3
      id: 3
      title: Sociale Zaken en Werkgelegenheid (szw)
      short: szw
variants:
  - name: Filter selection
    context:
      id: 1
      type: span
      linkText: Kies 'iets'
      linkTextActive: Pas opties aan
      modalTitle: Selecteer ministeries
      fieldLabel: fieldLabel
      fieldInstruction:
      fieldPlaceholder: 'Bijv: 0612345678'
      Options:
        - Option: 1
          id: 1
          title: Landbouw, Natuur en Voedselkwaliteit (lnv)
          short: lnv
          checked: checked
        - Option: 2
          id: 2
          title: Onderwijs, Cultuur en Wetenschap (ocw)
          short: ocw
        - Option: 3
          id: 3
          title: Sociale Zaken en Werkgelegenheid (szw)
          short: szw
  - name: Filter selection - Limit (3)
    context:
      id: 1
      type: div
      linkText: Kies 'iets'
      linkTextActive: Pas opties aan
      modalTitle: Selecteer ministeries
      fieldLabel: fieldLabel
      fieldInstruction:
      fieldPlaceholder: 'Bijv: 0612345678'
      maxShow: 3
      selectAll: true
      selectAllID: 123211
      Options:
        - Option: 1
          id: 1
          title: Nederland
          short: Nederland
          checked: checked
        - Option: 2
          id: 2
          title: Frankrijk
          short: Frankrijk
          checked: checked
        - Option: 3
          id: 3
          title: Griekenland
          short: Griekenland
          checked: checked
        - Option: 4
          id: 4
          title: Spanje
          short: Spanje
          checked: checked
        - Option: 5
          id: 5
          title: Zweden
          short: Zweden
        - Option: 6
          id: 6
          title: Nederland
          short: Nederland
        - Option: 7
          id: 7
          title: Frankrijk
          short: Frankrijk
        - Option: 8
          id: 8
          title: Griekenland
          short: Griekenland
        - Option: 9
          id: 9
          title: Spanje
          short: Spanje
        - Option: 10
          id: 10
          title: Zweden
          short: Zweden
        - Option: 11
          id: 11
          title: Nederland
          short: Nederland
        - Option: 12
          id: 12
          title: Frankrijk
          short: Frankrijk
        - Option: 13
          id: 13
          title: Griekenland
          short: Griekenland
        - Option: 14
          id: 14
          title: Spanje
          short: Spanje
        - Option: 15
          id: 15
          title: Zweden
          short: Zweden
        - Option: 16
          id: 16
          title: Nederland
          short: Nederland
        - Option: 17
          id: 17
          title: Frankrijk
          short: Frankrijk
        - Option: 18
          id: 18
          title: Griekenland
          short: Griekenland
        - Option: 19
          id: 19
          title: Spanje
          short: Spanje
        - Option: 20
          id: 20
          title: Zweden
          short: Zweden
        - Option: 21
          id: 21
          title: Nederland
          short: Nederland
        - Option: 22
          id: 22
          title: Frankrijk
          short: Frankrijk
        - Option: 23
          id: 23
          title: Griekenland
          short: Griekenland
        - Option: 24
          id: 24
          title: Spanje
          short: Spanje
        - Option: 25
          id: 25
          title: Zweden
          short: Zweden
        - Option: 26
          id: 26
          title: Nederland
          short: Nederland
        - Option: 27
          id: 27
          title: Frankrijk
          short: Frankrijk
        - Option: 28
          id: 28
          title: Griekenland
          short: Griekenland
        - Option: 29
          id: 29
          title: Spanje
          short: Spanje
        - Option: 30
          id: 30
          title: Zweden
          short: Zweden
        - Option: 31
          id: 31
          title: Nederland
          short: Nederland
        - Option: 32
          id: 32
          title: Frankrijk
          short: Frankrijk
        - Option: 33
          id: 33
          title: Griekenland
          short: Griekenland
        - Option: 34
          id: 34
          title: Spanje
          short: Spanje
        - Option: 35
          id: 35
          title: Zweden
          short: Zweden
        - Option: 36
          id: 36
          title: Nederland
          short: Nederland
        - Option: 37
          id: 37
          title: Frankrijk
          short: Frankrijk
        - Option: 38
          id: 38
          title: Griekenland
          short: Griekenland
        - Option: 39
          id: 39
          title: Spanje
          short: Spanje
        - Option: 40
          id: 40
          title: Zweden
          short: Zweden
        - Option: 41
          id: 41
          title: Nederland
          short: Nederland
        - Option: 42
          id: 42
          title: Frankrijk
          short: Frankrijk
        - Option: 43
          id: 43
          title: Griekenland
          short: Griekenland
        - Option: 44
          id: 44
          title: Spanje
          short: Spanje
        - Option: 45
          id: 45
          title: Zweden
          short: Zweden
        - Option: 46
          id: 46
          title: Nederland
          short: Nederland
        - Option: 47
          id: 47
          title: Frankrijk
          short: Frankrijk
        - Option: 48
          id: 48
          title: Griekenland
          short: Griekenland
        - Option: 49
          id: 49
          title: Spanje
          short: Spanje
        - Option: 50
          id: 50
          title: Zweden
          short: Zweden
  - name: Filter selection - Multilevel
    context:
      id: 1
      type: span
      linkText: Kies 'iets anders'
      linkTextActive: Pas opties aan
      modalTitle: Selecteer uit deze themas
      fieldLabel: fieldLabel
      fieldInstruction:
      fieldPlaceholder: 'Bijv: 0612345678'
      maxShow: 3
      multilevel: true
      Options:
        - Option: 1
          id: 1
          title: Nederland
          short: Nederland
          checkAll: true
          OptionsSubs:
            - OptionsSub: 11
              id: 11
              title: NederlandSub1
              short: NederlandSub1
              checked: checked
            - OptionsSub: 12
              id: 12
              title: NederlandSub2
              short: NederlandSub2
        - Option: 2
          id: 2
          title: Frankrijk
          short: Frankrijk
          checkAll: true
          OptionsSubs:
            - OptionSub: 21
              id: 21
              title: FrankrijkSub1
              short: FrankrijkSub1
            - OptionSub: 22
              id: 22
              title: FrankrijkSub2
              short: FrankrijkSub2
