label: Wetgevingkalender
context:
  headerContext:
    navLinks:
    - url: '#'
      text: Eenvoudig zoeken
    - url: '#'
      text: uitgebreid zoeken
    - url: '#'
      text: zoeken in EU-richtlijnen
