---
title: CVDR - GIO Kaart
label: CVDR - GIO Kaart
status: ready
context:
  headerContext:
    file: logo.svg
    alt: Overheid.nl logo
    language: true
    skipLinks:
      - url: '#content'
        text: Direct naar content
  pageactions:
    title: ''
    intro: ''
    items:
      - link: '#'
        text: Downloaden
        icon: icon-download.svg
      - link: '#'
        text: Printen
        icon: icon-print.svg
        actionPrint: true
  sidebar:
    modifier: list--facet
    heading: OfficiÃ«le bekendmakingen
    items:
      - content: <a href="#">Veelgestelde vragen</a>
