---
label: Tuchtrecht - Searchresults
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
  resultmodalContext:
    modifier: result--list--wide
    items:
    - title: Aangevraagde evenementenvergunningen 2018
      headerimg: https://via.placeholder.com/720x280.png?text=Kaart+met+marker
      titleHeader: h2
      text: 4 september 2018 -  Aangevraagde evenementenvergunningen 2018
      buttons:
        - button: Bekijk publicatie
          type: primary
        - button: Bekijk op kaart
          type: primary
          action: modal-4
          modal: true
  sortContext:
    modifier:
    amountPerPageFilter: true
    columns: true
    options:
    - label: Datum
      value: value
      active: is-active
    - label: Titel
      value: value
  resultsContext:
    modifier: result--list--wide
    items:
    - title: Voortgangsrapportage CTIVD over de werking Wiv2017
      titleHeader: h2
      label: Nieuw vandaag
      text: Het rapport bevat de bevindingen van de Commissie van Toezicht op de Inlichtingen- en Veiligheidsdiensten inzake de werking van de Wet op de inlichtingen en veiligheidsdiensten 2017
      share: false
      buttons:
        - button: Bekijk publicatie
          type: secendary
      metadataDates:
        - value: "Datum uitspraak: 15-05-2009"
        - value: "Datum publicatie: 15-05-2009"
        - value: "ECLI:NL:NOGIETS"
    - title: Voortgangsrapportage CTIVD over de werking Wiv2017
      titleHeader: h2
      label: Nieuw vandaag
      text: Het rapport bevat de bevindingen van de Commissie van Toezicht op de Inlichtingen- en Veiligheidsdiensten inzake de werking van de Wet op de inlichtingen en veiligheidsdiensten 2017
      share: false
      buttons:
        - button: Bekijk publicatie
          type: secendary
      metadataDates:
        - value: "Datum uitspraak: 15-05-2009"
        - value: "Datum publicatie: 15-05-2009"
        - value: "ECLI:NL:NOGIETS"
    - title: Voortgangsrapportage CTIVD over de werking Wiv2017
      titleHeader: h2
      label: Nieuw vandaag
      text: Het rapport bevat de bevindingen van de Commissie van Toezicht op de Inlichtingen- en Veiligheidsdiensten inzake de werking van de Wet op de inlichtingen en veiligheidsdiensten 2017
      share: false
      buttons:
        - button: Bekijk publicatie
          type: secendary
      metadataDates:
        - value: "Datum uitspraak: 15-05-2009"
        - value: "Datum publicatie: 15-05-2009"
        - value: "ECLI:NL:NOGIETS"
  inputSearchContext:
    modifier: input-text--searchmedium
    id: 1
    fieldLabel: Postcode
    fieldLabelVisible: false
    fieldInstruction:
    fieldPlaceholder: Verfijn op zoekwoord
    remove: true
  inputsubmitSearchSaveContext:
    label: Uw e-mailadres
    showLabel: true
    placeholder: Uw e-mailadres
    button: Bevestigen
  selectedfilterContext:
    items:
      - label: Gezocht op
        value: leveringen
        url: "#"
      - label: Bouwvergunning
        url: "#"
      - label: APV vergunning
        url: "#"
  subselectionContext:
    linkText: Selecteer beroepsgroep(en)
    id: 1
    modalTitle: Selecteer beroepsgroep(en)
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    searchFilter: true
    type: span
    Options:
      - Option: 1
        id: 1
        title: Beroepsgroep 1
        short: Beroepsgroep 1
      - Option: 2
        id: 2
        title: Beroepsgroep 2
        short: Beroepsgroep 2
      - Option: 3
        id: 3
        title: Beroepsgroep 3
        short: Beroepsgroep 3
  subselectionThemaContext:
    linkText: Selecteer instantie(s)
    id: 13
    modalTitle: Selecteer instantie(s)
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    searchFilter: true
    type: span
    Options:
      - Option: 4
        id: 4443
        title: Instantie 1
        short: Instantie 1
      - Option: 5
        id: 5443
        title: Instantie 2
        short: Instantie 2
      - Option: 6
        id: 6443
        title: Instantie 3
        short: Instantie 3
  selectCustomContext:
    options:
    - id: 1
      value:
      label: Alle
      linkedto: 1
    - id: 1
      value: 10
      label: Op
      linkedto: 2
      selected: selected
    - id: 2
      value: 20
      label: Tot
      linkedto: 3
    - id: 3
      value: 30
      label: Tussen
      linkedto: 4
  datumvanContext:
    label: Datum van
    radio: true
    id: 7654
    options:
    - id: checkbox-40123123123125
      text: Uitspraak
      name: onderwerp455
    - id: checkbox-40232321313215
      text: Publicatie
      name: onderwerp455
  subselectionBeroepsgroepContext:
    linkText: Selecteer beroepsgroep
    id: 1313123222
    modalTitle: Selecteer beroepsgroep
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    type: span
    radio: true
    Options:
      - Option: 4
        id: 41234214123
        title: Beroepsgroep 1
        short: Beroepsgroep 1
      - Option: 5
        id: 57789762
        title: Beroepsgroep 2
        short: Beroepsgroep 2
      - Option: 6
        id: 6576
        title: Beroepsgroep 3
        short: Beroepsgroep 3
      - Option: 6
        id: 634322676
        title: Beroepsgroep 4
        short: Beroepsgroep 4
      - Option: 6
        id: 643433333676767
        title: Beroepsgroep 5
        short: Beroepsgroep 5
      - Option: 6
        id: 6233433676565
        title: Beroepsgroep 6
        short: Beroepsgroep 6
      - Option: 6
        id: 62343242344367
        title: Beroepsgroep 7
        short: Beroepsgroep 7
  subselectionOnderwerpContext:
    linkText: Selecteer onderwerp
    id: 1313123222126
    modalTitle: Selecteer onderwerp
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    type: span
    radio: true
    Options:
      - Option: 4
        id: 4123421412312222
        title: Onderwerp 1
        short: Onderwerp 1
      - Option: 5
        id: 57789762212
        title: Onderwerp 2
        short: Onderwerp 2
      - Option: 6
        id: 657622222
        title: Onderwerp 3
        short: Onderwerp 3
  subselectionBeslissingContext:
    linkText: Selecteer beslissing
    id: 131312322212232
    modalTitle: Selecteer beslissing
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    type: span
    radio: true
    Options:
      - Option: 4
        id: 412342141231
        title: beslissing 1
        short: beslissing 1
      - Option: 5
        id: 577897621
        title: beslissing 2
        short: beslissing 2
      - Option: 6
        id: 65761
        title: beslissing 3
        short: beslissing 3
  buttonText:
    text: Opnieuw zoeken
  subselectionInfoContext:
    linkText: Selecteer domein
    id: 13131232
    modalTitle: Selecteer domein
    fieldLabel: fieldLabel
    fieldInstruction:
    fieldPlaceholder: 'Bijv: 0612345678'
    type: span
    radio: true
    OptionsLabel: Vrije beroepen
    buttonSubmit: true
    hideClose: true
    Options:
      - Option: 4
        id: 4
        title: Accountants
        short: Accountants
        checked: checked
        linkedto: 1
      - Option: 5
        id: 5
        title: Advocaten
        short: Advocaten
        linkedto: 2
      - Option: 6
        id: 6
        title: Diergeneeskunde
        short: Diergeneeskunde
        linkedto: 2
      - Option: 6
        id: 634322
        title: Gerechtsdeurwaarders
        short: Gerechtsdeurwaarders
        linkedto: 2
      - Option: 6
        id: 643433333
        title: Gezondheidszorg
        short: Gezondheidszorg
        linkedto: 2
      - Option: 6
        id: 6233433
        title: Notarissen
        short: Notarissen
        linkedto: 2
      - Option: 6
        id: 6234324234
        title: Scheepvaart
        short: Scheepvaart
        linkedto: 2
    Options2Label: Producenten
    Options2:
      - Option: 7
        id: 7
        title: Pluimvee en eieren
        short: Pluimvee en eieren
      - Option: 8
        id: 8
        title: Akkerbouw
        short: Akkerbouw
      - Option: 9
        id: 9
        title: Vee en vlees
        short: Vee en vlees
  inputsubmitContext:
    label: Verfijn uw zoekopdracht
    showLabel: false
    placeholder: Woord(en) of zinsdeel
    button: Zoek
    modifierComponent: input-inputsubmit--s
  zoekeninContext:
    label: Zoekwoord(en) in
    radio: true
    flex: true
    options:
    - id: checkbox-4012312312312
      text: Uitspraak
      name: onderwerp45
    - id: checkbox-4023232131321
      text: Inhoudsindicatie
      name: onderwerp45
  producentenContext:
    moreless: true
    searchFilter: true
    options:
    - id: checkbox-2020765
      text: Pluimvee en eieren
      name: onderwerp
    - id: checkbox-207651
      text: Akkerbouw
      name: onderwerp
    - id: checkbox-207654
      text: Vee en vlees
      name: onderwerp
  zoekopContext:
    options:
    - id: checkbox-30
      text: Uitspraak
      name: onderwerp3
    - id: checkbox-302
      text: Inhoudsindicatie
      name: onderwerp3




